### ISSUE TITLE
Cant use Flash CS6 for spritesheets

### ISSUE THREAD

**Issue by jan-doez-animationz** [ShadowMario/FNF-PsychEngine#10834]
### Describe your bug here.

Recently i tried using flash cs6 for sprite sheets to add to psych engine but it didnt work even though i changed some stuff to look more simmilar to other spritesheets please help i keep getting this crash :
C:\HaxeToolkit\haxe\std/haxe/xml/Parser.hx (line 217)
C:\HaxeToolkit\haxe\std/haxe/xml/Parser.hx (line 117)
C:\HaxeToolkit\haxe\std/Xml.hx (line 122)
flixel/graphics/frames/FlxAtlasFrames.hx (line 246)
editors/CharacterEditorState.hx (line 840)
editors/CharacterEditorState.hx (line 520)
flixel/ui/FlxButton.hx (line 521)
flixel/ui/FlxButton.hx (line 507)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: haxe.xml.XmlParserException: Expected node name at line 2 char 2
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

All i did is mainly add some songs and made sprites with a spritesheet and XML generators

**Comment by QuetzalcoutlDev** [comment]
I use Adobe Flash CS6 for sprites in my mods (this because my PC cannot run later versions)

The problem is that the coding of the .xml files of the Flash CS6 is UTF-16 and Haxeflixel use the UTF-8 coding and that is why the error.

Something that I do so that the Psych Engine can read them is that after exporting the sprite I open its .xml with Sublime Text and re guard the file with the utf-8 with bom coding which is the one that Haxeflixel can read.
