### ISSUE TITLE
Cache Things Through Source

### ISSUE THREAD

**Issue by Username2120** [ShadowMario/FNF-PsychEngine#11122]
### What is your question?

Is it possible to Cache an image through source? I've done some digging and the only things I've found either make the load time of the image worse or just don't work.

**Comment by Username2120** [comment]
okay...? do you want to explain what that does or, better yet, explain how I can (or cant) pre cache things?

**Comment by Yoshubs** [comment]
if you're using source and you want to cache and image, just call upon it with Paths.image(), you don't even have to append it to an object (unless it's before/after cache clearing stuff, since it clears unused images)

not sure if this answers your question, don't listen to anyone else's answers because that's just in regards to clearing the cache lmao

**Comment by MemeHoovy** [comment]
hi shubs

**Comment by Username2120** [comment]
This worked for me! Thanks!

> if you're using source and you want to cache an image, just call upon it with Paths.image(), you don't even have to append it to an object (unless it's before/after cache clearing stuff, since it clears unused images)
> 
> not sure if this answers your question, don't listen to anyone else's answers because that's just in regards to clearing the cache lmao
