### ISSUE TITLE
Animations for playable character bugging out.

### ISSUE THREAD

**Issue by BlueTheDude** [ShadowMario/FNF-PsychEngine#1120]
### Describe your problem here.

I was trying to create a playable character for the engine, but the regular animations sort of fused with the miss animations. making regular/miss hybrid animations for the regular animations, but the miss animations worked as intended. Everything i have tried since ended up with the same result. please help :(

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I added an json file for the character, as well as the xml file and the spritesheet. that is all i changed.

**Comment by Micasddsa** [comment]
This happened to me before but I can't remember what I did to make it like that. I will be going through my XML folder and see if I find the one that bugged. (IIRC, You have your miss and normal animation both start with "sing" and because of that, psych engine uses anything that starts with "sing". to fix this, you have to name your miss poses "misssing" or something else other than "singmiss")

**Comment by BlueTheDude** [comment]
> This happened to me before but I can't remember what I did to make it like that. I will be going through my XML folder and see if I find the one that bugged. (IIRC, You have your miss and normal animation both start with "sing" and because of that, psych engine uses anything that starts with "sing". to fix this, you have to name your miss poses "misssing" or something else other than "singmiss")

YUP, THAT SOLVED THE ISSUE!!!! Thank you so much!!
