### ISSUE TITLE
Hey ShadowMario The New Verison 0.6.3 Of Psych Engine Has a Lot of Glitch Can You Fix This

### ISSUE THREAD

**Issue by Zomple12** [ShadowMario/FNF-PsychEngine#11917]
### Describe your bug here.

Glitch
- The Camera Show To Far Up And Left
- When You Add a Custom Game Over Playable Character It Does Not Show The Camera To Follow lt
Fix This Please ):

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by TheKitBoi** [comment]
that aint alot of "glitch" there's only two
1. did you even check the camera offset
2. use 
```
boy = getProperty('boyfriendName') 
function onCreate()
	setPropertyFromClass('GameOverSubstate', 'characterName', boy..'-dead'); --Character json file for the death animation
end
```

**Comment by Jevilm** [comment]
can people please stop capitalizing every word they say

**Comment by Zomple12** [comment]
here what i got for lt:
function onCreate()
	-- CHARACTER
	setPropertyFromClass('GameOverSubstate', 'characterName', 'bf-dead');
	
	--SOUNDS
	setPropertyFromClass('GameOverSubstate', 'deathSoundName', 'fnf_loss_sfx'); --file goes inside sounds/ folder
	setPropertyFromClass('GameOverSubstate', 'loopSoundName', 'gameOver'); --file goes inside music/ folder
	setPropertyFromClass('GameOverSubstate', 'endSoundName', 'gameOverEnd'); --file goes inside music/ folder
end

**Comment by Bumper3241** [comment]
Thanks, this is the only thread on the entire internet about this bug and the only reply is some condescending prick who gave two cookie cutter basic ass answers, I fucking love it here.

https://github.com/ShadowMario/FNF-PsychEngine/assets/35423009/07ad08be-c6df-4b8c-af6f-8f79f371c3e5



The camera's offset has nothing to do with it, When the animation starts, the camera immediately shoots down and to the right, not matter what values i change in the stage files and the character files.

Checking the character editor does nothing, because no matter what the camera is set to, the animation always goes off screen.

It also doesn't matter what the offset of the animations are, as no matter where any of them are, the camera still always shoots down and to the right.

**Comment by LimeadeGX** [comment]
@Bumper3241 did you ever find a fix to the issue? i'm having the same problem myself, even with the script given on the wiki
