### ISSUE TITLE
I cant load custom week even though when i made a previous test week the exact same way it worked

### ISSUE THREAD

**Issue by LeDerp64** [ShadowMario/FNF-PsychEngine#12218]
### Describe your problem here.

Last night i made a test week so i could make sure everything worked and everything did, i deleted the test week then went to bed when i tried making the actual week today by using the exact same method it suddenly started crashing whenever i try to load a song with both the story mode and freeplay.

C:\HaxeToolkit\haxe\std/cpp/_std/sys/io/File.hx (line 30)
Song.hx (line 104)
StoryMenuState.hx (line 321)
StoryMenuState.hx (line 260)
flixel/FlxState.hx (line 202)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: [file_contents,assets/data/beneath-the-mask/beneath-the-mask.json]
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

this is the error message, i wouldn't mind if this happened while i did my testing week, but the fact that it didn't is making me so confused. I would like it if i could get an explanation on why this is happening.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by DragonTrance** [comment]
That error is what happens when the engine can't find a file. In this case, it looks like it can't find the default chart for the song you try and load. If you're using one chart without any difficulty modifications, you can rename that chart to the song name (so it just shows as `this-is-the-song.json`), and then load the "Normal" difficulty.

Unless you only want to load charts in one difficulty, you can just add the difficulty name at the end of the json like this: `song-hard.json` or `song-easy.json`
