### ISSUE TITLE
SwitchState Problem 

### ISSUE THREAD

**Issue by JustMe1352** [ShadowMario/FNF-PsychEngine#12267]
### Describe your problem here.

Hello!
I been working on my mod and I was coding it so then when you click a key it will switch states. When I mean switch states I mean like its in the main menu and you click enter and it takes you to the freeplay, that's a switch state. For some reason every time I make a new states or hx type you could say, the switch state thing breaks on that state and doesn't work. It just gives me a error. The thing is that there is a other switchstate on top of the code that is giving the error on and it works but the only deafferents is that, it's not a new state.
Could someone help me?

Error:
![Screenshot 2023-04-14 185100](https://user-images.githubusercontent.com/130803298/232167337-cd8f58b2-3149-4bc0-9276-3caf74a96ef0.png)

Code:
![image_2023-04-14_185152742](https://user-images.githubusercontent.com/130803298/232167390-98e915f7-4952-4a40-8dd4-250d215a0b36.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I did change somethings like not using MusicBeatState but using FlxG but it didn't do anything so I changed it back.

**Comment by Legendary-Candice-Joe** [comment]
In the original titlestate hx file, rename TitleData to something else.

**Comment by JustMe1352** [comment]
Just gives a other error
![image_2023-04-15_203148388](https://user-images.githubusercontent.com/130803298/232259919-920aaa05-e7fc-497c-aace-f83e417ed970.png)

**Comment by Legendary-Candice-Joe** [comment]
Yeah correct me if I'm wrong, but have you made a copy of titlestate and is the original titlestate still in use?
Going off that assumption. So you want to completely remove your copy or the original titlestate.
In more places then 1, you've got a "TitleData = {" or something like that.
If you can't do that or I'm going off the wrong assumption then you need to just Ctrl-F and remove every instance of "TitleData = {" except for one, which should be in your copy of titlestate.

Sorry if I'm wrong but that's what it looks like.
Because as it says in the error TitleData has been defined more than once in different files.
