### ISSUE TITLE
Uncaught Error: Null Object Reference

### ISSUE THREAD

**Issue by Emananimateslol** [ShadowMario/FNF-PsychEngine#12294]
### Describe your bug here.

FreeplayState.hx (line 74)
fixel/FlxGame.hx (line 642 )
fixel/FlxGame.hx (line 729 ) 
fixel/FlxGame.hx (line 682 )
fixel/FlxGame.hx (line 550 )
openfl/events/EventDispacther.hx ( line 402 )
openfl/display/DisplayObject.hx (line 1399 )

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I only edited Mainmenustate not freeplaystate

**Comment by Noel3454565FNF** [comment]
same here idk why ;-;

**Comment by Aguluntrun89** [comment]
same 
flixel/graphics/frames/FlxAtlasFrames.hx (line 250)
editors/MenuCharacterEditorState.hx (line 237)
editors/MenuCharacterEditorState.hx (line 187)
flixel/ui/FlxButton.hx (line 521)
flixel/ui/FlxButton.hx (line 507)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

i think its because of high quality making game crash or did something wrong on the Mainmenustate

**Comment by LowoTV** [comment]
It never happens to me. I don't understand why it's happening to you

**Comment by Aguluntrun89** [comment]
nvm i fixed it

**Comment by Noel3454565FNF** [comment]
yeah me to

**Comment by LowoTV** [comment]
> ### _**completed**_

God dammit

**Comment by LowoTV** [comment]
I mean that @Emananimateslol should close this as completed.

> > ### _**completed**_
> 
> God dammit

**Comment by crimsonfucker887** [comment]
it happened to me and I don't know how to fix it
