### ISSUE TITLE
Having trouble importing videos

### ISSUE THREAD

**Issue by Al-AmeenAdewunmi** [ShadowMario/FNF-PsychEngine#12887]
### Describe your problem here.

I'm trying to have a video play before the title screen loads, but things won't compile and the code I used in earlier versions isn't working. I tried looking at some other code to get a better idea, but now I'm stuck with
`source/states/TitleState.hx:194: characters 4-8 : Expected }`

This is what my code currently looks like.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/53586162/2a669a89-c51c-4cd6-a810-8acaf483644a)

Idk if it's right but I placed this in as well

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/53586162/37a36958-0e88-463b-874f-69c07e93d04c)

So yeah, idk what to do.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by biomseed** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/73907153/5206f107-e749-4edd-a8dc-58accb32da0e)
Yes, you clearly did.
Also, I think here is where you messed up.
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/73907153/2f60f6c0-d128-4e68-b52e-45de381ff758)
If statements are supposed to have curly brackets, I think. You missed them. Else statements are supposed to be placed after the end of an if statement, and since there was no end ("}") to the if statement, line 194 gives you an error. You need to add the curly brackets you missed for the if statement.

**Comment by Al-AmeenAdewunmi** [comment]
Well I don't know where to place them, I don't understand any of this.

**Comment by Al-AmeenAdewunmi** [comment]
Welp, still don't know how to do this. Every time I try to add in code I get some other random error and I'm sick of it.
