### ISSUE TITLE
A few errors that happened to me

### ISSUE THREAD

**Issue by Baumey72** [ShadowMario/FNF-PsychEngine#12944]
### Describe your bug here.

Hello Psych Engine Team, I came to tell you a few errors that happened to me when I installed versions 7.0 and 7.1 of Psych Engine, there are 2 but I would still like to know if it can be solved.

1. There is a Script that does not work for me.
I have a Script where when you press the "Space" key you do the "Hey!!" Pose (or "Taunt" Pose as others say), but in versions 7.0 and 7.1 that specific Script doesn't work for me and I don't know why it happens.

2. The game crashes when I choose some songs.
I have a Mod where I have all my FNF Covers, and I decided to use my Mod to test versions 7.0 and 7.1 but in 2 Covers, which are Magmatic and Boiling Point, for some reason when I choose those 2 Covers, the game It closes and I don't know why that happens either, if it's a Stages error or what it will be.

I hope you can answer me :(

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I don't know what happens to make these errors happen

**Comment by biomseed** [comment]
>I have a Script where when you press the "Space" key you do the "Hey!!" Pose (or "Taunt" Pose as others say), but in versions 7.0 and 7.1 that specific Script doesn't work for me and I don't know why it happens.

https://github.com/ShadowMario/FNF-PsychEngine/wiki/Transitioning-Lua-Mods-from-0.6.x-to-0.7
There is no versions called "7.0" or "7.1". In case you mean 0.7 and 0.7.1, look at the wiki page above to see the inconsistencies between versions so you can find out what is causing your script not to work, as not all mods made for 0.6 are compatible with 0.7. Also, this isn't a "bug" because it's not a problem with the engine, it's a problem with your script.

**Comment by Baumey72** [comment]
I'm not that good at coding, I more or less know Stages, but not that good, I'd better continue using version 0.6 because version 0.7 is not the best for me
