### ISSUE TITLE
When i try to load in my character the game crashes

### ISSUE THREAD

**Issue by coolmanboyguy** [ShadowMario/FNF-PsychEngine#12940]
### Describe your bug here.

i made a quick sprite sheet to test it out and when i put the sprite sheet where it needs to be when i try to load it in game it only crashes

### Command Prompt/Terminal logs (if existing)

```bash
flixel/graphics/frames/FlxAtlasFrames.hx (line 246)
states/editors/CharacterEditorState.hx (line 824)
states/editors/CharacterEditorState.hx (line 504)
flixel/ui/FlxButton.hx (line 521)
flixel/ui/FlxButton.hx (line 507)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by coolmanboyguy** [comment]
HELPPPPP HELPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP

**Comment by GamerShaheer** [comment]
Did You Make an xml file for the spritesheet, or the json?
if not, then, make an xml file for the sprite sheet, you can use gamebananas spritesheet and xml file generator. If your mod/build is compiled, go to mods, select your mod(For eg: MyMod, or whatever you named it) go to images, then characters, and place the spritesheet and xml file into the folder. Then, open up your game, and click on 7 in the menu screen and go to character editor, then you will see a stage with these boxes/options:
![Screenshot 2023-08-03 171834](https://github.com/ShadowMario/FNF-PsychEngine/assets/140260360/983e235f-a2ea-49bd-8d7c-7abab326d339)

 If your character only has idle, up, down, let, and right animations, don't use bf, change the character by going to this option and changing the character to mom, as she has simpler animations: 
![wowie](https://github.com/ShadowMario/FNF-PsychEngine/assets/140260360/1ababdc0-2015-445e-a65a-4598285e3406)
  
Then, go to this option:
![Lol](https://github.com/ShadowMario/FNF-PsychEngine/assets/140260360/84af9505-0c9f-48fd-872c-f23a201d39ae)

Instead of saying BF, it will say Mom_assets or mom_assets, replace that text with the name of your characters spritesheet and xml file(The 2 files should be the same name). Adjust all your animations and click on the Save JSON file and name the file the same as your character(Also the same as your spritesheet and xml file name).
Place the JSON in assets/characters. Close and open psych engine, ad everything should be good.

**Comment by coolmanboyguy** [comment]
where can i find that generator
