### ISSUE TITLE
fix camera dont go in the characters who sing

### ISSUE THREAD

**Issue by aless26pic** [ShadowMario/FNF-PsychEngine#12976]
### What feature do you want to get added on the **base** engine?

fix this camera 
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/109902083/2300908f-a66e-4312-98f1-3717e59d5598)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by aless26pic** [comment]
i have a video https://youtu.be/YuIqLUkRTas

**Comment by Draconic-Hybrid** [comment]
Camera focus is dependent on the chart, not the engine. 

In the Chart Editor under the Section tab, enabling "Must Hit Section" will switch the camera over to Boyfriend's POV. This will swap the icons in the chart editor, but _not the notes._

In order to swap the notes, click the Swap Section button under the same tab.

**Comment by aless26pic** [comment]
> Camera focus is dependent on the chart, not the engine.
> 
> In the Chart Editor under the Section tab, enabling "Must Hit Section" will switch the camera over to Boyfriend's POV. This will swap the icons in the chart editor, but _not the notes._
> 
> In order to swap the notes, click the Swap Section button under the same tab.

im gonna test

**Comment by aless26pic** [comment]
it work thanks
