### ISSUE TITLE
percentage symbol instead of in-game menu buttons like "resume" "restart song" etc

### ISSUE THREAD

**Issue by vesel4ak** [ShadowMario/FNF-PsychEngine#13175]
### Describe your problem here.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/119149152/d7fc03e0-c759-4ac5-95f1-02be1a70dd0d)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by ChumbleDev** [comment]
weird, ive had the same problem but only in freeplay when i import mods.

**Comment by Wolfie1985yt** [comment]
> weird, ive had the same problem but only in freeplay when i import mods.
usually its from an old alphabet.png and alphabet.xml in the mods folder that causes percent signs because psych engine gets confused with the new alphabet.png and .xml so you just have to delete the alphabet.png and xml from the mods folder or make sure its using the new ones from 0.7.1h or what version you are using and it should fix. if not, idk

**Comment by Lasercar** [comment]
This also happens if there's another image before the alphabet.png - such as the achievementgrid.png (which has been replaced with a folder and separate images).
