### ISSUE TITLE
THE CUSTOM CHART NOT WORKING

### ISSUE THREAD

**Issue by argabisa** [ShadowMario/FNF-PsychEngine#13363]
### Describe your bug here.

So im just download and move my mods assets to new version of Psych engine, everything work fine, like the custom character, background,etc. But thre's something that kinda error 

CUSTOM CHART

I don't know if IM just dumb but i literally put it on data folder and yet when i testing if it works it doesn't it says: EROR WHILE LOADING CHART : missing file: "custom chart"/"custom chart.json"
Idk how to fix this 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes

**Comment by MrKitten1753** [comment]
you cannot have spaces in chart names. all spaces must be replaced with a "-". Try renaming the chart maybe with the hyphen.

**Comment by argabisa** [comment]
Like rename them to certain difficulty?

**Comment by MrKitten1753** [comment]
no; I mean the JSON file name. This for example wouldn't work because it uses a space: 
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/49869806/3bd821bd-8e0a-4469-9162-804b34dfdc07)

but this would because it uses a -:
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/49869806/e0794f8f-2df1-46bb-b281-801aeda15b88)

Another thing is to make sure the song name in the week you are modifying lines up with the folder name storing the JSON, and that the JSON inside said folder is named properly as well.

**Comment by argabisa** [comment]
My chart doesn't have space man

**Comment by MrKitten1753** [comment]
Can you send the week file and the chart folder? I might understand what's happening a little better if I can see what's going on.

**Comment by RetailYT** [comment]
i have a somewhat similar problem except im trying to replace a chart with my custom chart in someone else's mod im not sure if its because its not possible but im trying to see if it is possible

**Comment by QayyumRetreatboyz** [comment]
I hope someone respond to me asap, I have a problem. And I am very confused because how do I change json files
