### ISSUE TITLE
When enter "Story Mode" it will Enter "Song" or "Week" instead of story menu

### ISSUE THREAD

**Issue by NotEpik** [ShadowMario/FNF-PsychEngine#1344]
### Describe your problem here.

How to make a game enter a week or a song of the week when entering "Story Mode" I try to use from this one [#937] but it doesn't seem to work

this is the error I got after inserting the code

```
source/MainMenuState.hx:230: characters 89-95 : Unknown identifier : diffic
source/MainMenuState.hx:230: characters 89-95 : For function argument 'jsonInput'
```

can someone help me how to do this, please :(

I know this is duplicated of #937 but I got the error so...

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited Achievement.hx, PlayState.hx, MainMenuState.hx, FreeplayState.hx, Discord.hx, CoolUtili.hx, and more idk

**Comment by DEV-idiotXD** [comment]
### > Describe your problem here.
How to make a game enter a week or a song of the week when entering "Story Mode" I try to use from this one [#937] but it doesn't seem to work

this is the error I got after inserting the code

source/MainMenuState.hx:230: characters 89-95 : Unknown identifier : diffic
source/MainMenuState.hx:230: characters 89-95 : For function argument 'jsonInput'
can someone help me how to do this, please :(

I know this is duplicated of #937 but I got the error so...

Are you modding a build from source or with Lua?
Source

What is your build target?
Windows x64

Did you edit anything in this build? If so, mention or summarize your changes.
I edited Achievement.hx, PlayState.hx, MainMenuState.hx, FreeplayState.hx, Discord.hx, CoolUtili.hx, and more idk
as someone who has tried it yes these are the exact errors i get when compiling

**Comment by ShadowMario** [comment]
Show your code unless you expect me to guess your exact issue.

**Comment by NotEpik** [comment]
> Show your code unless you expect me to guess your exact issue.

This one is the code I took from #937 

```
var weekNumber:Int = 0;
var songsPlaylist:Array<String> = [
	'Satin Panties',
	'High',
	'Milf'
];

PlayState.storyPlaylist = songsPlaylist;
PlayState.isStoryMode = true;
PlayState.storyDifficulty = 2;

PlayState.SONG = Song.loadFromJson(PlayState.storyPlaylist[0].toLowerCase() + diffic, PlayState.storyPlaylist[0].toLowerCase());
PlayState.storyWeek = weekNumber;
PlayState.campaignScore = 0;
PlayState.campaignMisses = 0;
LoadingState.loadAndSwitchState(new PlayState(), true);
```

After I open this issue I edit some of code to this.

```
var weekNumber:Int = 0;
var songsPlaylist:Array<String> = [
	'Tutorial'
];

PlayState.storyPlaylist = songsPlaylist;
PlayState.isStoryMode = true;
PlayState.storyDifficulty = 2;

PlayState.SONG = Song.loadFromJson(PlayState.storyPlaylist[0].toLowerCase() + '-hard', PlayState.storyPlaylist[0].toLowerCase());
PlayState.storyWeek = weekNumber;
PlayState.campaignScore = 0;
PlayState.campaignMisses = 0;
LoadingState.loadAndSwitchState(new PlayState(), true);
```

It's got no error but the game crash after entering story mode.

**Comment by ShadowMario** [comment]
This mod i did some minor help with includes this. https://gamebanana.com/mods/341936
