### ISSUE TITLE
lime test windows doesnt work

### ISSUE THREAD

**Issue by juprismramid** [ShadowMario/FNF-PsychEngine#13467]
### Describe your bug here.

when i enter "lime test windows" in powershell, it shows an error

### Command Prompt/Terminal logs (if existing)

```bash
lime : The term 'lime' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ lime test windows
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (lime:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Vortex2Oblivion** [comment]
Try running 

```haxelib run lime setup ```

Then try again

**Comment by mcagabe19** [comment]
just run ```haxelib run lime setup -alias -y```

**Comment by juprismramid** [comment]
now it just gives me an error saying "Error: You must have a "project.xml" file or specify another valid project file when using the 'test' command"

**Comment by Darksnip3zz** [comment]
�[30;41m ERROR �[0m source/psychlua/CallbackHandler.hx:55: characters 18-33

55 | �[2m if(Lua_helper.�[0m�[1msendErrorsToLua�[0m�[2m)�[0m
| �[31m^^^^^^^^^^^^^^^�[0m
| Class<llua.Lua_helper> has no field sendErrorsToLua

 �[30;41m -> �[0m export/release/windows/haxe/ApplicationMain.hx:153: characters 5-36

  153 | �[2m    �[0m�[1mApplicationMain.getEntryPoint()�[0m�[2m;�[0m
      |     �[31m^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^�[0m
      | Called from macro here
�[30;41m ERROR �[0m C:/HaxeToolkit/haxe/lib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27

142 | �[2m public function �[0m�[1mconcat�[0m�[2m(frames:FlxFramesCollection)�[0m
| �[31m^^^^^^�[0m
| Field concat should be declared with 'override' since it is inherited from superclass flixel.graphics.frames.FlxAtlasFrames

�[30;41m ERROR �[0m C:/HaxeToolkit/haxe/lib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27

142 | �[2m public function �[0m�[1mconcat�[0m�[2m(frames:FlxFramesCollection)�[0m
| �[31m^^^^^^�[0m
| Field concat overrides parent class with different or incomplete type

 �[30;41m -> �[0m C:/HaxeToolkit/haxe/lib/flixel/5,6,1/flixel/graphics/frames/FlxAtlasFrames.hx:454: characters 18-24

  454 | �[2m public function �[0m�[1mconcat�[0m�[2m(collection:FlxAtlasFrames, overwriteHash = false)�[0m
      |                  �[31m^^^^^^�[0m
      | Base field is defined here

      | Different number of function arguments
�[30;41m ERROR �[0m source/flxanimate/PsychFlxAnimate.hx:65: characters 40-53

65 | �[2m if(!isXml) frames = FlxAnimateFrames.�[0m�[1mfromSpriteMap�[0m�[2m(cast myData, img);�[0m
| �[31m^^^^^^^^^^^^^�[0m
| Class<flxanimate.frames.FlxAnimateFrames> has no field fromSpriteMap

�[30;41m ERROR �[0m source/flxanimate/PsychFlxAnimate.hx:84: characters 46-62

84 | �[2m anim.curInstance = FlxDestroyUtil.destroy(�[0m�[1manim.curInstance�[0m�[2m);�[0m
| �[31m^^^^^^^^^^^^^^^^�[0m
| flxanimate.animate.FlxElement should be Null<flixel.util.IFlxDestroyable>
| For function argument 'object'

�[30;41m ERROR �[0m source/flxanimate/PsychFlxAnimate.hx:85: characters 48-66

85 | �[2m anim.stageInstance = FlxDestroyUtil.destroy(�[0m�[1manim.stageInstance�[0m�[2m);�[0m
| �[31m^^^^^^^^^^^^^^^^^^�[0m
| flxanimate.animate.FlxElement should be Null<flixel.util.IFlxDestroyable>
| For function argument 'object'

�[30;41m ERROR �[0m source/states/stages/objects/SpraycanAtlasSprite.hx:26: characters 28-31

26 | �[2m canAtlas.anim.onComplete.�[0m�[1madd�[0m�[2m(finishCanAnimation);�[0m
| �[31m^^^�[0m
| () -> Void has no field add

�[30;41m ERROR �[0m source/states/stages/Tank.hx:328: characters 31-34

328 | �[2m if (pico.anim.onComplete.�[0m�[1mhas�[0m�[2m(picoStressCycle)) // for safety�[0m
| �[31m^^^�[0m
| () -> Void has no field has

�[30;41m ERROR �[0m source/states/stages/Tank.hx:329: characters 28-34

329 | �[2m pico.anim.onComplete.�[0m�[1mremove�[0m�[2m(picoStressCycle);�[0m
| �[31m^^^^^^�[0m
| () -> Void has no field remove

�[30;41m ERROR �[0m source/states/stages/Tank.hx:332: characters 24-27

332 | �[2m pico.anim.onComplete.�[0m�[1madd�[0m�[2m(picoStressCycle);�[0m
| �[31m^^^�[0m
| () -> Void has no field add

this is what happened to me when i tried to run lime test windows, can someone please help me
