### ISSUE TITLE
Specific Ccashing on mods

### ISSUE THREAD

**Issue by TrexWhy** [ShadowMario/FNF-PsychEngine#13493]
### Describe your problem here.

[](url)

Erro: Uncauch Error: Null Object Reference

to resume, when I get to a specific part of the song, it crashes, doesn't matter chaging options, reinstalling the mod, instaling via different like one on mediafire orther on google drive, jsut doesn't matter. Any guesses? I really appreciate it.

OBS: if want to know the mod is "Vs. Ourple Guy V3"

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Jammington24** [comment]
Is it by any chance in the song Cashmoney?
If so, I was having the same issue because I had my shaders turned off; I just enabled them, and I could play it just fine.
If not, could you tell what song is it, and what timestamp does it crash in? Maybe there's a specific event that's not being read correctly by the engine, or it just has a typo on its .lua script.

**Comment by mcagabe19** [comment]
> Is it by any chance in the song Cashmoney? If so, I was having the same issue because I had my shaders turned off; I just enabled them, and I could play it just fine. If not, could you tell what song is it, and what timestamp does it crash in? Maybe there's a specific event that's not being read correctly by the engine, or it just has a typo on its .lua script.

probably bad coding idk
