### ISSUE TITLE
HelpME!

### ISSUE THREAD

**Issue by TomVN1230101** [ShadowMario/FNF-PsychEngine#13632]
### Describe your problem here.

How fix this #13629 
![Screenshot 2023-11-18 181903](https://github.com/ShadowMario/FNF-PsychEngine/assets/121646407/d8393d95-00d9-4b21-adf3-bb29e613302c)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Jamextreme140** [comment]
In this case, you must install/use SScript 5.2.0, because "SCall" was renamed to "TeaCall" in the latest version.
Check the required [Libraries versions](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions)

If you want to use the latest version, you should switch to "experimental" branch

**Comment by TomVN1230101** [comment]
i already check it

**Comment by TomVN1230101** [comment]
> In this case, you must install/use SScript 5.2.0, because "SCall" was renamed to "TeaCall" in the latest version. Check the required [Libraries versions](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions)
> 
> If you want to use the latest version, you should switch to "experimental" branch

i already check it
