### ISSUE TITLE
How to make winning icons with frames.frames.length for 0.7.1h

### ISSUE THREAD

**Issue by Mlaofmd** [ShadowMario/FNF-PsychEngine#13642]
### What is your question?

im dumb,
healthbar:
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/52864321/9eb87ac2-e8ba-498c-b7cc-be0547ee5405)
playstate:
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/52864321/e362472d-6d9e-47eb-a553-60e0f2518cf8)

**Comment by richTrash21** [comment]
To add a third icon frame you need to change how icon frames are generated. In order to do this (without messing up standard icons) I suggest, first of all, revert all changes you've made (sorry but code that you've wrote won't work😔) and second of all add these changes to the `changeIcon()` function:

```haxe
var graphic = Paths.image(name, allowGPU);
// if graphic width is 3 times greater than it's height - 3rd frame will be added
var delimiter:Int = (Math.floor(graphic.width / 3) >= graphic.height) ? 3 : 2;
loadGraphic(graphic, true, Math.floor(graphic.width / delimiter), graphic.height);

// after changing how frames are generated you don't need to change anything except this
animation.add(char, [for (i in 0...numFrames) i], 0, false, isPlayer); // btw numFrames is the same as frames.frames.length
``` 

Now you need to implement these changes to the `PlayState`:

```haxe
if (healthBar.percent < 20) // losing
{
    iconP1.animation.curAnim.curFrame = 1;
    iconP2.animation.curAnim.curFrame = iconP2.numFrames > 2 ? 2 : 0;
}
else if (healthBar.percent > 80) // winning
{
    iconP1.animation.curAnim.curFrame = iconP1.numFrames > 2 ? 2 : 0;
    iconP2.animation.curAnim.curFrame = 1;
}
else // neutral
{
    iconP1.animation.curAnim.curFrame = 0;
    iconP2.animation.curAnim.curFrame = 0;
}
```

**Hooray!** Now icons can have a winning frame! :D
