### ISSUE TITLE
Make BF Dodge Animation Play when you miss my custom note on source

### ISSUE THREAD

**Issue by ripsyhehe** [ShadowMario/FNF-PsychEngine#1368]
### Describe your problem here.

Title Basically explains it. But if you don't understand I'm trying to make boyfriends dodge animation play when my custom note is missed. I'm using source, not LUA.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by SrtHero278** [comment]
Use `function noteMiss` to detect the note miss and use `objectPlayAnimation` to  play the dodge animation.

**Comment by ripsyhehe** [comment]
Where? Also Im not On LUA. Only source

**Comment by KutikiPlayz** [comment]
I'm assuming since you want the dodge animation to play, your note needs to be missed and not hit. You'll want to go to playstate.hx and search for "Hurt Note"
![Screenshot (965)](https://user-images.githubusercontent.com/73810550/143540652-cc62968c-4e90-4e7a-8bb0-27775a6d9b84.png)
It should look something like this.
You'll want to copy-paste that code, change Hurt Note to whatever your note type is, and then change the hurt animation to dodge.
![Screenshot (966)](https://user-images.githubusercontent.com/73810550/143540802-0034d23b-e88e-4c28-b647-ad23718b539d.png)
should look something like that

Hope this works for you

**Comment by KutikiPlayz** [comment]
Under the notemiss function in playstate.hx you wanna type
if(daNote.noteType == 'Your Note') {
      if(boyfriend.animOffsets.exists('dodge')) {
            boyfriend.playAnim('dodge', true);
            boyfriend.specialAnim = true;
            boyfriend.heyTimer = 0.6;
      }
}
![Screenshot (967)](https://user-images.githubusercontent.com/73810550/143541441-e4ff8486-35f3-4792-b0f7-a6bd892725ae.png)
should look something like that.
do note that I may or may not have spelled something wrong, and I don't think the hey timer is needed there but it should work

**Comment by ripsyhehe** [comment]
it didnt work, btw im on 4.2

**Comment by Doritojoey** [comment]
> 

Just use lua for that
