### ISSUE TITLE
source/psychlua/HScript.hx:295: characters 89-96 : Type not found : TeaCall Error while trying to build fnf psych engine

### ISSUE THREAD

**Issue by DukyKoug** [ShadowMario/FNF-PsychEngine#14137]
### Describe your problem here.

I have looked everywhere for an answer to this issue but have only found answers to the same issue but the end says SCall instead of TeaCall, anyone know how to fix this?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by DukyKoug** [comment]
> Probably you don't have the correct SScript version

I updated it to the newest version and nothing changed, is there a certain version of it I should have?

**Comment by xw1w1** [comment]
same problem

**Comment by Stefan2008Git** [comment]
Are you using the latest SScript @DukyKoug and @xw1w1?

**Comment by Light0073** [comment]
haxelib install TeaScript

**Comment by DukyKoug** [comment]
> > haxelib install TeaScript
> 
> `haxelib install SScript`*

I tried both of those and I still get the same error

**Comment by Stefan2008Git** [comment]
> > > haxelib install TeaScript
> > 
> > 
> > `haxelib install SScript`*
> 
> I tried both of those and I still get the same error

Try to change `TeaCall` to `Tea`

**Comment by Light0073** [comment]
haxelib install SScript 8.1.6

**Comment by Stefan2008Git** [comment]
> haxelib install SScript 8.1.6

Oh, yeah

**Comment by Light0073** [comment]
> > haxelib установить SScript 8.1.6
> 
> 

> > haxelib установить SScript 8.1.6
> 
> Ах, да

did it work?

**Comment by Stefan2008Git** [comment]
> > > haxelib установить SScript 8.1.6
> 
> > > haxelib установить SScript 8.1.6
> > 
> > 
> > Ах, да
> 
> did it work?

It works for him, but i don-t know for him

**Comment by DukyKoug** [comment]
> > > > haxelib install TeaScript
> > > 
> > > 
> > > `haxelib install SScript`*
> > 
> > 
> > I tried both of those and I still get the same error
> 
> Try to change `TeaCall` to `Tea`

Sry it took me so long to respond, this worked!!! Thank you so much!!!

**Comment by CheeseBoy12** [comment]
> > > > haxelib instala TeaScript
> > > 
> > > 
> > > `haxelib install SScript`*
> > 
> > 
> > Probé ambos y sigo recibiendo el mismo error.
> 
> Intenta cambiar `TeaCall`a`Tea`

como hago eso

**Comment by Persefo** [comment]
> > > > haxelib install TeaScript
> > > 
> > > 
> > > `haxelib install SScript`*
> > 
> > 
> > I tried both of those and I still get the same error
> 
> Try to change `TeaCall` to `Tea`

Sorry, How can I do this?

**Comment by Kweenyy** [comment]
> > > > > haxelib install TeaScript
> > > > 
> > > > 
> > > > `haxelib install SScript`*
> > > 
> > > 
> > > I tried both of those and I still get the same error
> > 
> > 
> > Try to change `TeaCall` to `Tea`
> 
> Sry it took me so long to respond, this worked!!! Thank you so much!!!

what do you do to change Teacall to Tea

**Comment by Stefan2008Git** [comment]
> > > > > > haxelib install TeaScript
> > > > > 
> > > > > 
> > > > > `haxelib install SScript`*
> > > > 
> > > > 
> > > > I tried both of those and I still get the same error
> > > 
> > > 
> > > Try to change `TeaCall` to `Tea`
> > 
> > 
> > Sry it took me so long to respond, this worked!!! Thank you so much!!!
> 
> what do you do to change Teacall to Tea

Simply go to HScript and change TeaCall to Tea

**Comment by chrisdoesstuff69** [comment]
how do you do that

**Comment by Redblazer-lab** [comment]
where is HSCRIPTTTTT BROOO

**Comment by Redblazer-lab** [comment]
I cant find Hscript

**Comment by Stefan2008Git** [comment]
It's located on source/psychlua/HScript @Redblazer-lab

**Comment by Redblazer-lab** [comment]
ok i figured that out but now when i did `lime test windows` it goes and stops 

`PS C:\Users\Buddy\OneDrive\Documents\FNF-PsychEngine-main> lime test windows
source/psychlua/CallbackHandler.hx:55: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua
export/release/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here
C:/HaxeToolkit/haxe/lib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27 : Field concat should be declared with 'override' since it is inherited from superclass flixel.graphics.frames.FlxAtlasFrames
C:/HaxeToolkit/haxe/lib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27 : Field concat overrides parent class with different or incomplete type
C:/HaxeToolkit/haxe/lib/flixel/5,5,0/flixel/graphics/frames/FlxAtlasFrames.hx:457: characters 18-24 : ... Base field is defined here
C:/HaxeToolkit/haxe/lib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27 : ... Different number of function arguments
source/backend/Paths.hx:605: characters 7-18 : flxanimate.FlxAnimate has no field loadAtlasEx (Suggestion: loadAtlas)
source/objects/Character.hx:304: characters 87-101 : flxanimate.animate.FlxAnim has no field lastPlayedAnim
source/objects/Character.hx:335: characters 20-26 : flxanimate.animate.FlxAnim has no field resume`

**Comment by harelisgoof** [comment]
what if it is already named tea and not tea call??? please help

**Comment by FinderFromMac** [comment]
En la terminal o cmd ponlo en inglés

**Comment by havectrl** [comment]
does anyone know how to download TeaCall???

**Comment by xw1w1** [comment]
Simply go to HScript and change TeaCall to Tea

**Comment by megalives717** [comment]
not working please help

**Comment by ManuArtXD** [comment]
I changed them all to tea and now is says it doesn't find Tea ._.

**Comment by ManuArtXD** [comment]
> > > > haxelib install TeaScript
> > > 
> > > 
> > > `haxelib install SScript`*
> > 
> > 
> > I tried both of those and I still get the same error
> 
> Try to change `TeaCall` to `Tea`

I triked that, but now it says:
source/psychlua/HScript.hx:349: characters 84-87 : Type not found : Tea

I have SScript 7.7.0, got it from an archive since SScript if gone
