### ISSUE TITLE
Cannot play songs

### ISSUE THREAD

**Issue by thunderbrap** [ShadowMario/FNF-PsychEngine#14236]
### Describe your problem here.

I've not been able to play specific songs in psych 0.6.2. Only 3 of them don't work. I'm positive that it's an openfl, flixel or even haxe issue but I'm not sure which libraries to install anymore

openfl/events/SampleDataEvent.hx (line 189)
openfl/media/Sound.hx (line 748)
flixel/system/FlxSound.hx (line 619)
flixel/system/FlxSound.hx (line 482)
PlayState.hx (line 2384)
PlayState.hx (line 3107)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)
Uncaught Error: To be consistent with flash the listener function registered to SampleDataEvent has to provide between 2048 and 8192 samples.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/161191667/9ca74fad-1dfd-42f0-bc1d-142e43c0c32d)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Compiled and changed libraries due to other issue

**Comment by Vortex2Oblivion** [comment]
0.6.2 isn't supported anymore

**Comment by thunderbrap** [comment]
Could I please have a more specific answer? I am aware of this. I just want to be able to fix issues with a previous build

**Comment by thunderbrap** [comment]
I also ported everything to 0.7.3 just to see if there was a change. None at all, issue still persists

**Comment by thunderbrap** [comment]
Somehow the issue was a leftover lua file that I had no idea was misbehaving.

**Comment by YouDevsYoupikmin** [comment]
Did you edited Playstate or source code ?
Maybe it's due to broken events / functions.
Try import songs JSON to a default engine build maybe it's due to json.
If you have only a "inst.ogg" file try this : open song json and at the end change "needs_vocals : true" with false
yes i'm from gamebanana lol

**Comment by YouDevsYoupikmin** [comment]
Did you edited Playstate or source code ?
Maybe it's due to broken events / functions.
Try import songs JSON to a default engine build maybe it's due to json.
If you have only a "inst.ogg" file try this : open song json and at the end change "needsVoices : true" with false

yes i'm from gamebanana lol

**Comment by AmongUs779** [comment]
Change your openfl version to 9.2.2 and don't change it again.
