### ISSUE TITLE
Auto Compiler

### ISSUE THREAD

**Issue by Redlmpostor** [ShadowMario/FNF-PsychEngine#14264]
### What feature do you want to get added on the **base** engine?

I want Psych engine source code to have an auto compiler that would download the stuff and compile the game for you instead of having to keep getting errors and shit like what I have.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by Average-FNF-Modder** [comment]
Bro put the wrong option ☠☠☠. You might wanna fix the Non-Request check or your request will probably just be ignored, though I can't deny having an installer type app like lots of other source code apps would be probably the best update to Psych Engine since code outside functions running once. Pls Shadow Mario I beg.
