### ISSUE TITLE
INVALID ANIMATION NAME ERROR

### ISSUE THREAD

**Issue by ClicheAveri** [ShadowMario/FNF-PsychEngine#14288]
### Describe your problem here.

I tried fixing this for like an hour total but I couldn't figure it out, and no resources online were useful. I'm using the latest 0.7.3 update and I'm trying to add my own custom note splash to the mod folder. But whenever I load the spritesheet, it keeps giving me this animation error.

EXTRA INFO:

-I'm using the latest version of Animate.
-Instead of using the mod template, all the images, data, etc. folders are directly in the "mods" folder.
-The Note Splashes have 4 frames, and only 1 animation.
![evidence 3](https://github.com/ShadowMario/FNF-PsychEngine/assets/159212492/e47f904f-055f-4643-bcc6-81c2361fae94)
![evidence 2](https://github.com/ShadowMario/FNF-PsychEngine/assets/159212492/dd1b1348-0f2d-4d0f-ae50-57d8f2654814)
![evidence 1](https://github.com/ShadowMario/FNF-PsychEngine/assets/159212492/ed57d980-b958-41e3-a1ae-48321f112db7)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by ender69funk** [comment]
Just type cliche

**Comment by Frakif91** [comment]
Put it in YOUR MOD FOLDER

Since the engine would most likely don't read file in /mods/ i would suggest you put it directly into "Test" or "YourModHere" folder like in PsychEngine/mods/YourModHere

and put the image in PsychEngine/mods/YourModHere/images/
for it to be read

**ALSO AND VERY IMPORTANT**

Now, with the new engine, you have a skin for 1 note (or maybe multiple works) so if they are the same color maybe consider doing just 1 animation with only 1 note spash and input the animation name like "splash cliche" instead of "splash cliche red" etc (or maybe "spash-cliche-red0" 
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/158631597/39d33cb6-37a3-4bd1-bc3c-71fab77a3a74)

**Comment by ClicheAveri** [comment]
I tried everything you said I should do. I put the mod stuff into it's own folder, I changed the animation name to "splash-cliche" and made it only one, and I even put it into mods/test/images when the first two didn't work. But none of these worked.
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/159212492/3a547adb-c2e9-4422-91dd-3bc2a4c59f91)

**Comment by ClicheAveri** [comment]
New Discovery and Information:

I'll say that beforehand I was using PNG's instead of animate tools to make these splashes. I thought that maybe that was the problem, so I tried using a PNG-free note splash to solve the problem. That didn't work.

I also tried turning the symbol from a Graphic to a Movie Clip. Nothing changed.
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/159212492/1c68a4a4-fdf6-41a6-bec9-53c4d2afd509)
