### ISSUE TITLE
no animation found error

### ISSUE THREAD

**Issue by KhaiKien** [ShadowMario/FNF-PsychEngine#14292]
### Describe your problem here.

i put the sprites in \mods\modTemplate\My-Mod\images but it not working help me

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Frakif91** [comment]
i put the sprites in \mods\modTemplate\My-Mod\images but it not working help me

You should put files here

PsychEngine/mods/<yourmodfolder>/images/character/<yourcharacterhere.png>
PsychEngine/mods/<yourmodfolder>/images/character/<yourcharacterhere.xml>
PsychEngine/mods/<yourmodfolder>/character/<yourcharacterhere.json>

and i don't know if it's a compile issue since i don't know what happend if you code from `Source ` so i can't help you more on that

**Comment by Frakif91** [comment]
If your doing a mod, please consider changing
"Are you modding a build from source or with Lua?"
to "Lua"

if your not compiling the project of course and your using a custom-made mod

**Comment by KhaiKien** [comment]
i did

> i put the sprites in \mods\modTemplate\My-Mod\images but it not working help me
> 
> You should put files here
> 
> PsychEngine/mods//images/character/<yourcharacterhere.png> PsychEngine/mods//images/character/<yourcharacterhere.xml> PsychEngine/mods//character/<yourcharacterhere.json>
> 
> and i don't know if it's a compile issue since i don't know what happend if you code from `Source ` so i can't help you more on that

i did all of them but it still say no animation found

**Comment by KhaiKien** [comment]
ok you just need to change your .png / .xml file name into "your-character_Assets" i think so?
