### ISSUE TITLE
loading screen

### ISSUE THREAD

**Issue by MisterOficerPL** [ShadowMario/FNF-PsychEngine#1441]
### Describe your problem here.

i want to make an loading screen but i cant find anything on google

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes I edited coolutil.hx adding new difficulty and i added characters

**Comment by BL0KYBL0K** [comment]
the loading screen is built in to the web browser build but im not sure how to do it in windows build

**Comment by Kaysanrafiakbar** [comment]
Just delete no_preload_all on loadingstate.hx
is easy tho
but unfortunately it will be useless, since load a song wont take so much time

also if you get any error of like this, delete #end line

ERROR 1: source/loadingstate.hx:171: characters 3-7 : Expected }

ERROR 2: source/loadingstate.hx:186: characters 2-6 : Expected }

And make sure replace funkay.png with the custom one you make

If you have any question, go dm me in discord!  (Kaysan#3035)

**Comment by MisterOficerPL** [comment]
thanks it works but one more question can you or someone else tell me how to make opponent icon bounces more than player icon to the beat like in cheeky v3

**Comment by ShadowMario** [comment]
The loading screen has no use on Windows, it's only used for downloading assets on HTML5
