### ISSUE TITLE
Main Menu Song Plays in Modded Songs

### ISSUE THREAD

**Issue by DevBeni** [ShadowMario/FNF-PsychEngine#14525]
### Describe your problem here.

I'm porting my mod from the lua (or downloadeable version of Psych Engine) to the source code version, but when I go into the songs, the stage isn't there and the song ends up being the Main Menu theme, instead of the actual one. Does anyone have an idea of why this happens? (Also, the Main Menu Song plays in the chart editor too, but I've already checked the files of the song)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ac-phoenix-yt** [comment]
I think name of a folder or the song itself might be wrong-writen, you should check if the song names are actually right, if they aren't you have to fix them [obviously] this type of errors normally happens when you try to add spaces on the song name, the chart files and folders on data and songs must be all with no caps lock and instead of spaces use "-", only the song name INSIDE the chart file haves to keep the caps lock and the spaces, this also applys to weeks, add your song name with the caps you added and the spaces
