### ISSUE TITLE
Yo! Week 8 update just dropped

### ISSUE THREAD

**Issue by Loganthegamer12678** [ShadowMario/FNF-PsychEngine#14573]
### What feature do you want to get added on the **base** engine?

Could you port Psych Engine to the new version of the FNF engine pls?

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by VoidedBattery** [comment]
Do you mean that you want to port Weekend1 to Psych Engine? Because like... I can't help but think that you want the entirety of Psych Engine ported over to FNF 0.3.2 because it was in vice versa for the whole time 😂

Although it WOULD be cool if the official FNF had the same mod support for LUA and whatnot. If you think that should be the case, you should go look for their github instead!

**Comment by Loganthegamer12678** [comment]
Ouch! Saw-ry! I only wanted Darnell's songs and the new features like the updated Freeplay to be added in the next Psych Engine update...
