### ISSUE TITLE
Songs getting replaced with the menu music

### ISSUE THREAD

**Issue by ejme765** [ShadowMario/FNF-PsychEngine#14768]
### Describe your problem here.

Each time I play my song it plays the main menu music.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by JordanSantiagoYT** [comment]
this could be because the engine is trying to find a song that doesn't exist, either that or your song name contains spaces and the file path to your song contains a space in the song name, by that i mean

don't format it as "song name", format it as "song-name"

otherwise it won't find the song and that will happen

**Comment by ejme765** [comment]
ok thanks :)
