### ISSUE TITLE
How to compile Psych Engine 0.6.3 now?

### ISSUE THREAD

**Issue by Quaradam** [ShadowMario/FNF-PsychEngine#14873]
### Describe your problem here.

I searched internet to find my problem, but still nothing. Here in image file:
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/65819389/585dc984-b08e-456a-b2ae-7d51db4f2de5)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I can't tell how much, but i already saved it in github

**Comment by Quaradam** [comment]
here my "mod": https://github.com/Quaradam/sonicexemultiverse

**Comment by Quaradam** [comment]
Even downgranding `Flixel` to 5.5.0 not helping

**Comment by gameygu-0213** [comment]
![setup-windows.bat](https://github.com/gameygu-0213/VS-Char-Revitilized-Dev-Branch/blob/master/setup/setup-windows.bat)
heres a script that installs the neccessary versions to build 0.6.3
NOTE: THIS INSTALL SCRIPT ALSO INSTALLS THINGS YOU MIGHT NOT NEED, SO DOUBLE CHECK BEFORE RUNNING! if you're not sure, don't modify this script. 
i'd say the main things you could delete are the lines for the haxeui packages (haxeui-core, haxeui-flixel), and if you don't use build_x64-debug, you can also remove the line that installs hxcpp-debug-server

from there change the following described in this ![issue](https://github.com/ShadowMario/FNF-PsychEngine/issues/11792#issuecomment-1405952842) and you should be able to build


if you just install current binaries they end up causing several compatibility issues, as it's been a bit since 0.6.3.

**Comment by Quaradam** [comment]
> ![setup-windows.bat](https://github.com/gameygu-0213/VS-Char-Revitilized-Dev-Branch/blob/master/setup/setup-windows.bat) heres a script that installs the neccessary versions to build 0.6.3 NOTE: THIS INSTALL SCRIPT ALSO INSTALLS THINGS YOU MIGHT NOT NEED, SO DOUBLE CHECK BEFORE RUNNING! if you're not sure, don't modify this script. i'd say the main things you could delete are the lines for the haxeui packages (haxeui-core, haxeui-flixel), and if you don't use build_x64-debug, you can also remove the line that installs hxcpp-debug-server
> 
> from there change the following lines of playstate.hx under the sources folder described in this ![issue](https://github.com/ShadowMario/FNF-PsychEngine/issues/11792#issuecomment-1405952842) and you should be able to build (Tested working with the version from the last commit of the repo)
> 
> quick note: if you just downgrade flixel without downgrading other flixel packages, those could break

Thanks! That's work!
