### ISSUE TITLE
Problem with the Character Editor

### ISSUE THREAD

**Issue by SirCub** [ShadowMario/FNF-PsychEngine#1488]
### Describe your bug here.

Whenever I import a character and click "Reload Image" (Which I may add, worked before.), It just instantly closes the game. No error message, just closes. As if the game is going "Oh you wanna make a character? well oop boop no character for you". Is there a way to resolve this problem?

https://user-images.githubusercontent.com/75452118/143914327-d3eed4b9-6aac-4f52-aee4-ffccd49499f7.mp4

Also, I don't really know if I am using Lua or Source, because I don't really know how to tell if I am using either. I just picked Lua because I had to pick either of the two.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, just imported a character and it closed :/

**Comment by PersonNanoexe** [comment]
i recommend taking dd's json file and changing the name of it to your character. rename the image directory inside the json and then fix everything else in the editor. Thats how i get it to work

**Comment by Micasddsa** [comment]
_remember to put all the xml and png in the /mods folder!_

**Comment by SirCub** [comment]
@PersonNanoexe Well it didn't crash this time, but now I have a new problem. The sprites just don't wanna load
![what](https://user-images.githubusercontent.com/75452118/143923720-78a48007-5250-4345-80d7-f0948aac8b7d.png)

**Comment by Micasddsa** [comment]
well, did you put all images in /mods?

**Comment by SirCub** [comment]
@Micasddsa I did, in fact, put them in the /mods folder.
![see](https://user-images.githubusercontent.com/75452118/143925301-dc7b6df0-25b0-4558-acd6-de05b9783b57.png)
See?

**Comment by TTRICKYTHECAR** [comment]
**_TUTORIAL HOW TO ADD CHARACTERS IN PH_**

- Get your DD or any other fnf character reskin (The character editor is gonna think the spritesheet is corrupted because its in the wrong place)
- put DADDY_DEAREST.png and DADDY_DEAREST.xml in /mods/images/characters
- go in the game
- go in character editor
- Select the Dad Character
- type the image path of your character
- edit the position of every animation to your choice
- press "Save Character" and save your character .json as any name you want (The name of the character file is the name of the character in the chart editor)
- Go in the game
- Final Results

**Comment by NS-Unfair** [comment]
Basically, put the png and xml files in the characters folder into the mods/images/characters folder.

**Comment by SirCub** [comment]
@TTRICKYTHECAR I tried that and Boyfriend turned into a black box, I think I need to restart my pc.

**Comment by SirCub** [comment]
It didn't work...

**Comment by SirCub** [comment]
Well, it turns out I was putting the characters in mods/characters instead of mods/images/characters. LOL what was I thinking XD
Sorry for possibly wasting everyone's time, I kinda forgot that mods/images/characters was a thing.
