### ISSUE TITLE
problem with making a custom girlfriend character in character editor.

### ISSUE THREAD

**Issue by amberis-turquoise** [ShadowMario/FNF-PsychEngine#14895]
### Describe your bug here.

When adding other animations for a custom girlfriend in character editor it would scroll pass other animations that don't have the same name as the ones in the xml, i typed the names correctly and copy and pasted them, it still does the same thing... i don't know why it does this, but any help is appreciated 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, i did two custom opponents, custom scripts, aswell as towos fanmade fnf songs for placeholders.

**Comment by FazbearMods027** [comment]
If you're trying to use GF's original animations her DanceLEFT and DanceRIGHT animations have animation indices making only specific frames of the animation play... And remember to put a 0 at the end of the animation name to make sure it doesn't use other animations... Also keep in mind the Animation Text box is Case sensitive (Which means using upper case and lower case seriously matter) so the caps must be correct... Also a warning I have is to not leave the Animation box empty otherwise it will play every animation frame on the sprite sheet... For offsets I recommend going into the Ghost tab and making a ghost of GF's original sprites (that is if you haven't gone over them...) and then reloading the image so you can adjust them without too much shaking when animations change...
