### ISSUE TITLE
I need help with this - - >ERROR:No Animation Found

### ISSUE THREAD

**Issue by inneroil3** [ShadowMario/FNF-PsychEngine#14912]
### Describe your problem here.

I keep trying to import my character into psych engine but it keeps on saying ERROR:No Animation Found, and no matter what I try nothing seems to work
![image_2024-06-16_152858263](https://github.com/ShadowMario/FNF-PsychEngine/assets/173001528/bf70e400-715e-45f1-bd3e-330a71b90244)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by FazbearMods027** [comment]
I know how to deal with this issue... Start by opening the images .XML file and take note of the Animation names... then on the character editor set the image and go to the animations tab and open the drop down menu and select the specific animation then replace the Animation Symbol/Tag Text box with the name of the animation on the .XML file... then click Add/Update and the animation should run normally... if that still doesn't work check the .XML's Texture atlas Image path and make sure the image path matches the .PNG and has the .png at the end of it... otherwise the .xml cannot find the .png and resorts to the Haxe placeholder... This should help... And these tips are for Version 0.7.3 of Psych Engine... (Extra Tips: If you update the animation but it uses a different one because it has a similar name add a 0 on the animation symbol/tag text box along with the animation name so it recognizes it... And if you only want specific frames to play, Put the frame numbers into the animation indicies text box [Remember that 0 is always the first frame, Not 1] then when you update it only those frames play...) Also remember to save the Characters .Json file to avoid any file losses... Hope this helps...

**Comment by Guest2621** [comment]
@FazbearMods027 what should I do when I wrote the PNG correctly name but it still has this error?

**Comment by inneroil3** [comment]
thanks ive been on that for a week(:

**Comment by inneroil3** [comment]
wait, it didn't work ):

**Comment by FazbearMods027** [comment]
> @FazbearMods027 what should I do when I wrote the PNG name correctly but it still has this error?

Make sure that the specific Directory is in the file path it checks in Images not Images/Characters (For example the fill in for the path for the Default Boyfriend is [characters/BOYFRIEND]) if it's in an additional folder inside images/characters make sure to add the folder name (For Example if a modified spritesheet for Boyfriend is in a folder within images/characters then you would put in [characters/{Folder Name}/BOYFRIEND]) If the [Characters/] part is not in it will check images instead of images/characters... Hope this helps...
