### ISSUE TITLE
it keeps kicking me out when the opponent plays a note

### ISSUE THREAD

**Issue by umora909** [ShadowMario/FNF-PsychEngine#14986]
### Describe your bug here.

so i was playing mario smw its a fun mod fr but in like the 1st 2nd and 3rd song when the opponent plays a note it kicks me out and gives me this error:

flixel/graphics/frames/FlxAtlasFrames.hx:247:null
objects/NoteSplash.hx:121:null
objects/NoteSplash.hx:57:null
states/PlayState.hx:4067:null
states/PlayState.hx:4061:null
states/PlayState.hx:3042:null
states/PlayState.hx:3985:null
states/PlayState.hx:3309:null
states/PlayState.hx:3516:null
states/PlayState.hx:2182:null
flixel/FlxState.hx:220:null
flixel/FlxGame.hx:752:null
This happened in FlxGame.Update

like what the hell i need help 
![image_2024-06-27_195019268](https://github.com/ShadowMario/FNF-PsychEngine/assets/105164913/527df4e1-b425-4fdc-b45c-cc97c292a337)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

not a single thing

**Comment by HourOfEternity** [comment]
Just from the objects/NoteSplash.hx:57:null and objects/NoteSplash.hx:121:null, it looks like the game can't find the notesplash you are using, but you yourself have said that the game crashes when an opponent plays a note. Something that could help is seeing if you crash if you hit a note first, but since I mostly code in lua (almost nothing in haxe), I feel like it might be some code you have put in. Hope this helps you!

**Comment by umora909** [comment]
> in

when i hit a note first that also happens

**Comment by HourOfEternity** [comment]
> that

Well, looks like you possibly added or replaced a note splash texture or added your own. If this is correct, then you can go to the main menu, press 7 (which will bring you to a debug menu), and go to noteSplash Debug. Then, put in the noteSplash name and see if the game can find it. Hope this helps!
