### ISSUE TITLE
Error while compiling 7.3

### ISSUE THREAD

**Issue by AOYKA** [ShadowMario/FNF-PsychEngine#15122]
### Describe your problem here.

everytime i try to compile, this happens:

```
source/psychlua/CallbackHandler.hx:55: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua
export/release/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here
``` 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I took out the "Call" in "TeaCall"

**Comment by StormzYT** [comment]
I have the same problem, but with this message:
source/psychlua/HScript.hx:317: characters 89-96 : Type not found : TeaCall

**Comment by AOYKA** [comment]
> I have the same problem, but with this message: source/psychlua/HScript.hx:317: characters 89-96 : Type not found : TeaCall

take out all the "call" by selecting one of these "teacall", right click and click on "change all ocurrences", then rewrite just "Tea"

**Comment by StormzYT** [comment]
I did that but this now popped up:
source/psychlua/CallbackHandler.hx:55: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua
export/release/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here
source/psychlua/CallbackHandler.hx:55: characters 41-46 : Class<llua.LuaL> has no field error
export/release/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here
C:/Users/Marqus/Desktop/haxe/lib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27 : Field concat should be declared with 'override' since it is inherited from superclass flixel.graphics.frames.FlxAtlasFrames
C:/Users/Marqus/Desktop/haxe/lib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27 : Field concat overrides parent class with different or incomplete type
C:/Users/Marqus/Desktop/haxe/lib/flixel/5,8,0/flixel/graphics/frames/FlxAtlasFrames.hx:472: characters 18-24 : ... Base field is defined here
C:/Users/Marqus/Desktop/haxe/lib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27 : ... Different number of function arguments
source/backend/Paths.hx:605: characters 7-18 : flxanimate.FlxAnimate has no field loadAtlasEx (Suggestion: loadAtlas)
source/objects/Character.hx:304: characters 87-101 : flxanimate.animate.FlxAnim has no field lastPlayedAnim
source/objects/Character.hx:335: characters 20-26 : flxanimate.animate.FlxAnim has no field resume
source/psychlua/FunkinLua.hx:280: lines 280-283 : Int should be Bool
source/psychlua/FunkinLua.hx:280: lines 280-283 : ... For function argument 'f'
