### ISSUE TITLE
The song for my mod keeps playing the goddamn test music 

### ISSUE THREAD

**Issue by goobera** [ShadowMario/FNF-PsychEngine#15159]
### Describe your problem here.

when i tried playing my mod the song would just play the main menu theme but when i changed the mod redirector it worked but when i played through the free play menu it happened again

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by FazbearMods027** [comment]
Commonly for songs added through Lua mods you need to make sure there is an associated folder for the song in song (Specifically Mods/Mod-Name/Songs/Song-Name/Song-Files) The Folder containing the Song Files must contain an Inst audio file (The Voices audio file is optional) and the file extensions must be .ogg files otherwise the engine can't locate them... It plays the Test music by default when making one from scratch... if you know you put the song files in just change the name in the category where you can save the chart file to the one that matches the name of the folder (It is not Case-Sensitive) and press reload audio... then boom it's done... But for Source code it's too complicated for me to figure out... Sorry...
