### ISSUE TITLE
Im trying to make custom HealthBar by adding an image on camHUD but still failing

### ISSUE THREAD

**Issue by Quartal0620** [ShadowMario/FNF-PsychEngine#15186]
### Describe your problem here.

![image](https://github.com/user-attachments/assets/558614c0-9017-4a18-a717-8ac3f13820c5)
I tried to add image on camHUD
but healthBar keep covers it 
it worked properly at 0.6.2 but it is broken at 0.6.3
what shoud i do?

 function onCreate()
makeAnimatedLuaSprite('crystal','healthBarSkins/crystal', 315, 424)
    addAnimationByPrefix('crystal','idle','crystal idle' ,10, true)
    addLuaSprite('crystal', 'idle', 'crystal idle', true)
    objectPlayAnimation('crystal','idle' ,false)
    setLuaSpriteScrollFactor('crystal', 1, 1);
setObjectOrder('crystal', getObjectOrder('healthBar') + 0.5);
setObjectCamera('crystal', 'camHUD');
scaleObject('crystal', 0.33, 0.33);
    if downscroll then
setProperty('healthBarBG.visible', false);
makeAnimatedLuaSprite('crystal','healthBarSkins/crystal', 315, -145)
    addAnimationByPrefix('crystal','idle','crystal idle' ,10, true)
    addLuaSprite('crystal', 'idle', 'crystal idle', true)
    objectPlayAnimation('crystal','idle' ,false)
    setLuaSpriteScrollFactor('crystal', 1, 1);
setObjectOrder('crystal', getObjectOrder('healthBar') + 0.5);
setObjectCamera('crystal', 'camHUD');
scaleObject('crystal', 0.33, 0.33);
end
end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by FazbearMods027** [comment]
I don't entirely know this problem despite going through this issue myself... All that I really did was slightly modify the positions on the X and Y placements and that was all... But that was for an all black decoration on the unmodified health bar... This problem seems to still not be fixed on 0.7.X and later... And according to the script I had for it; A commented out line mentioned the layering can't use a decimal... I even attempted to make the layer change a negative but that also didn't work... If I had to take a guess... It would be because a specific thing was removed in later versions that prevents anything from going above the health bar to avoid certain situations... I recall a similar issue with a Winning Icons script where the winning icons ignore the health bar alpha and go behind the health bar... So my guess is it's not fully possible to link something to the health bar... But i'm not fully certain... From a custom health bar script I found for Three Different Health Bars They Worked fine and went over the health bar (I was using Psych Engine V0.7.3 when testing the scripts), Sadly I didn't check the scripts for it and even if I did I don't remember it, And even if I still have the scripts for them I can't seem to find them, or I may have deleted the scripts... (It may be possible to find those scripts but I recall two of them having a special property of forcing the icons at the ends... This is similar to SaraHUD's IconPoz Preference... I don't remember where I got it though...)

**Comment by Quartal0620** [comment]
thanks

**Comment by FrailMods** [comment]
Oh I know this issue... Simple solution... Normally when I have custom health bars of custom size that I use instead of modifying healthBar.png I set the value of the order input like this "setObjectOrder('[TAG NAME]', getObjectOrder('healthBar')+100)" mainly using 100 because as far as I know that is the minimum you can set it, otherwise it goes behind healthBar but from testing doing so also results in the icons going behind the custom Helathbar... Normally when I make a custom healthBar the area that's over the healthBar is black and leave the setObjectOrder value at 1 but from what I can see that is not the case... Long story short: try setting the value in getObjectOrder to 100 or higher and change the order of the Icons enough for them to go over the healthBar... This information works for Psych Engine on Version 0.6.3 and beyond... Hope this helps...

**Comment by Thiago70754** [comment]
function onCreatePost()
