### ISSUE TITLE
Again this animation error :(

### ISSUE THREAD

**Issue by Jzoin** [ShadowMario/FNF-PsychEngine#15199]
### Describe your bug here.

flixel/graphics/tile/FlxDrawQuadsItem.hx (line 119)
flixel/FlxCamera.hx (line 772)
flixel/FlxGame.hx (line 875)
flixel/FlxGame.hx (line 563)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i was making an animation for my mod, help me ShadowMario!

**Comment by FazbearMods027** [comment]
Not everybody knows how Psych Engine's Source code works... (At least It's not as wild as Kade Engine...) What were you aiming specifically for the animation you mentioned? is it for a song cutscene or between song cutscene? There isn't quite enough information to get a proper answer... (Also keep in mind, ShadowMario is slow to respond to things and commonly doesn't respond to issues altogether... Just Remember the Psych engine team is only Two people since two members of the team left...)

**Comment by Jzoin** [comment]
> Not everybody knows how Psych Engine's Source code works... (At least It's not as wild as Kade Engine...) What were you aiming specifically for the animation you mentioned? is it for a song cutscene or between song cutscene? There isn't quite enough information to get a proper answer... (Also keep in mind, ShadowMario is slow to respond to things and commonly doesn't respond to issues altogether... Just Remember the Psych engine team is only Two people since two members of the team left...)

im making my own spritesheet/xml, so this error is common for me, every time this error appear, and idk what to do

**Comment by FazbearMods027** [comment]
> > Not everybody knows how Psych Engine's Source code works... (At least It's not as wild as Kade Engine...) What were you aiming specifically for the animation you mentioned? is it for a song cutscene or between song cutscene? There isn't quite enough information to get a proper answer... (Also keep in mind, ShadowMario is slow to respond to things and commonly doesn't respond to issues altogether... Just Remember the Psych engine team is only Two people since two members of the team left...)
> 
> im making my own spritesheet/xml, so this error is common for me, every time this error appear, and idk what to do

Thanks for specifying what you mean by Animation... Normally The Engines Character Editor is the best to handle that... But for Source code I'm not sure... I believe the best way of doing this is to handle the Character data through a different Psych engine copy because along with a Custom characters Spritesheet and XML is also it's accompanied .Json file which holds the data for animation offsets, camera position, associated icon, health bar color, Antialiasing (If it's pixel), and which animations are linked to which animation on the xml... Not to mention the most important part... the .Json file is required to be present otherwise it won't be found by the engine... I don't fully understand Source code but I hope this helps...
