### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by NiftyAC** [ShadowMario/FNF-PsychEngine#15832]
### What is your question?

Will there ever be a way to use videos on the 1.0 version like on 0.7.3? It’s okay if there won’t be but my entire song is just a video.

**Comment by PerezSen** [comment]
--Just don't set it to play immediately because it can fail and I added the other functions because it doesn't pause unless you use the methods. I hope it works well for you :)

local videoPath = {};

function onCreate()
    videoPath = callMethodFromClass('backend.Paths', 'modsVideo', {'Otonoke'})
    createInstance('mesmerizer_video', 'hxvlc.flixel.FlxVideoSprite', {0, 0})
    setProperty("mesmerizer_video.camera", instanceArg("camHUD"),true ,true)
    scaleObject('mesmerizer_video', 1.125, 1.125)
    setObjectOrder('mesmerizer_video', 1)
    setScrollFactor('mesmerizer_video', 0.0, 0.0)
    setProperty("mesmerizer_video.x", screenWidth/2 - (1280/2))
    setProperty("mesmerizer_video.y", screenHeight/2 - (720/2))
    callMethod('mesmerizer_video.load', {videoPath})
    addInstance('mesmerizer_video')

end

function onSongStart()
    callMethod('mesmerizer_video.play')
end

function onPause()
    callMethod('mesmerizer_video.pause')
end

function onResume()
    callMethod('mesmerizer_video.resume')
end

function onDestroy()
    callMethod('mesmerizer_video.stop') 
end
