### ISSUE TITLE
zooming gets stuck when doing new charts?

### ISSUE THREAD

**Issue by FoxyGamer1980** [ShadowMario/FNF-PsychEngine#1775]
### Describe your problem here.

i was testing out the new chart editor in 0.5b's editor menu, and when i did some charting and some event adding, doing zooms will become stuck after being activated, is there a way to fix this? p.s., i'm new to charting, so i don't really know how this'll work

(The video shown below is a simple recreation of what i faced)

https://user-images.githubusercontent.com/94565422/144917926-242874d7-1fc9-4670-a641-6844fedbae87.mp4

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no, i'm using the official build of the mod

**Comment by Starmapo** [comment]
The camera doesn't automatically revert to the default zoom during the beginning of the song. The code that controls it (in PlayState at line 2300) is only active when `camZooming` is true
The `camZooming` variable is false at the beginning and only set to true once the opponent sings a note, which here you are adding camera zoom before the opponent sings, so it gets stuck. To fix it, you could make it so that `camZooming` is set to true once the 'Add Camera Zoom' event is triggered (line 2755)

**Comment by FoxyGamer1980** [comment]
thanks ^^ but what if i want camZooming set to true onCreate, how can i do that in a Lua Script

**Comment by Starmapo** [comment]
```setProperty('camZooming', true)```
You can use the template script from the 'Lua Script API' page from the wiki as a base

**Comment by FoxyGamer1980** [comment]
thank you for helping me out ^^
