### ISSUE TITLE
how do i make bf play an animation with a custom note

### ISSUE THREAD

**Issue by DrebDaDev** [ShadowMario/FNF-PsychEngine#1875]
### Describe your problem here.

So i made a special note that basically works like the fnf hd warning notes but no matter what i do i cant make bf play the dodging animation when he hits them, i already tried copying the hurt note code replacing all the hurt references with my note and the animation but nothing seems to work, he just does the pose of the arrow its over, anyone know how to fix this??
![image](https://user-images.githubusercontent.com/93683434/145408302-93a82679-aeaa-4594-9bdc-acebfd6b594e.png)
![image](https://user-images.githubusercontent.com/93683434/145408373-28db5b1e-ac4d-44b1-814e-93dc9dcd944a.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

added a custom note

**Comment by DrebDaDev** [comment]
![image](https://user-images.githubusercontent.com/93683434/145429050-e2b531ff-77a7-49d2-a004-b064c96b7a51.png)
like this or on playstate.hx (thats where the animation code is)

**Comment by DrebDaDev** [comment]
still doesnt work

**Comment by DrebDaDev** [comment]
https://user-images.githubusercontent.com/93683434/145431093-bd8dd82c-acc8-4019-8570-747f67bf76a7.mp4

if it helps here´s gameplay

**Comment by KutikiPlayz** [comment]
Are you putting the code where the hurt note code is or are you putting it where the hey note and such is? If you put it near the hurt note it won't work since that detects if you hit the note and if it was considered a miss. Here's my note for example. The hey note is there for reference to where the code is. 
![Screenshot (987)](https://user-images.githubusercontent.com/73810550/145453474-b42e0d84-a445-4837-80c5-8eeaf7eb0d9c.png)

**Comment by DrebDaDev** [comment]
yeah that makes sense i was putting it next to the hurt note

**Comment by DrebDaDev** [comment]
it works now thanks!
