### ISSUE TITLE
Loading new images freezes game

### ISSUE THREAD

**Issue by KutikiPlayz** [ShadowMario/FNF-PsychEngine#1879]
### What is your question?

I'm making an expurgation cover with my vocals, and I've re-coded the entire thing in this engine, only problem is that when the first stop sign appears, it freezes the game for a sec. It's pretty annoying to have to restart the song every time so that it doesn't freeze, and sometimes when it does freeze the popup text will bug and won't go away.  

https://user-images.githubusercontent.com/73810550/145472015-34044513-431e-4773-bb20-a565c6bd6616.mp4

Here's a video of the freeze and the text glitching.
The sprites are currently in shared, would moving the images to preload help at all? If so how would I make the game search in preload for them instead of shared?

**Comment by SanicBTW** [comment]
If you are using FlxSprite instead of the given BGSprite function when making a stage you should be able to specify the library where the asset is in, for example:
`var e:FlxSprite = new FlxSprite(x, y);`
`e.frames = Paths.getSparrowAtlas('folder', 'library');`
and in library you can use the folder that the asset is in, and you can put preload
and if you are using BGSprite I guess you can use the same method like
`var a:BGSprite = new BGSprite(Paths.getSparrowAtlas('folder', 'library'));`
I hope this helps

**Comment by KutikiPlayz** [comment]
> If you are using FlxSprite instead of the given BGSprite function when making a stage you should be able to specify the library where the asset is in, for example: `var e:FlxSprite = new FlxSprite(x, y);` `e.frames = Paths.getSparrowAtlas('folder', 'library');` and in library you can use the folder that the asset is in, and you can put preload and if you are using BGSprite I guess you can use the same method like `var a:BGSprite = new BGSprite(Paths.getSparrowAtlas('folder', 'library'));` I hope this helps

The code works, however it's still freezing unfortunately.
Thanks for the help

**Comment by ShadowMario** [comment]
You have to spawn the sign beforehand, if you want to hide the sprite set its alpha to 0.000001 instead of making it invisible, making it invisible will prevent it from loading earlier.
