### ISSUE TITLE
Update 0.51 Ideas

### ISSUE THREAD

**Issue by PDL2CGamejolt** [ShadowMario/FNF-PsychEngine#1958]
### What feature do you want to get added on the base engine?

Stage switch event, Kade engine lua script support, softcoded achievements, optional death icons, a tertiary character section and a none character (for songs without gf or a tertiary character)

**Comment by DatGamerYoloYT** [comment]
"Kade engine lua script support"
It's impossible because of how different the engines are.
"optional death icons"
![image](https://user-images.githubusercontent.com/84749503/145687951-86e70ecb-d1ed-4d35-ad50-bd9d4c6bac55.png)
"a tertiary character section and a none character (for songs without gf or a tertiary character)"
for removing gf, make a clone of the stage (or if it's just for the song then skip making a clone), then make gf's y pos really low so that she isn't visible anymore

**Comment by SrtHero278** [comment]
"Stage switch event"
Shadow already said:
![image](https://user-images.githubusercontent.com/93018286/145688401-daa5e162-7e56-4c15-ad4e-9fe5902bb865.png)

**Comment by PDL2CGamejolt** [comment]
> "Kade engine lua script support" It's impossible because of how different the engines are. "optional death icons" ![image](https://user-images.githubusercontent.com/84749503/145687951-86e70ecb-d1ed-4d35-ad50-bd9d4c6bac55.png) "a tertiary character section and a none character (for songs without gf or a tertiary character)" for removing gf, make a clone of the stage (or if it's just for the song then skip making a clone), then make gf's y pos really low so that she isn't visible anymore

can you answer the tritary character?

**Comment by TBiscuit1** [comment]
To answer you, there is the "GF Note" that will make girlfriend move. If GF is replaced with any character, it will move like if they were a normal opponent
