### ISSUE TITLE
How to put funkay into the game

### ISSUE THREAD

**Issue by Marioapk** [ShadowMario/FNF-PsychEngine#1992]
![funkay](https://user-images.githubusercontent.com/59497824/145704763-5e84ea1f-41ae-463f-9306-64de9e8f5083.png)
### What is your question?

The loading page will appear when Fnf 0.2.8 loads the week
The file is: (funkay.png) Psych Engine has this picture
But I don't know how to load it.

**Comment by KutikiPlayz** [comment]
It's a loading screen for when you build the game for HTML5 since the browser version tends to take a lot longer to load things than the downloaded version does, thus a loading screen on the downloaded version would be useless since it loads almost instantly. If you really wanna put it on the downloaded version though I know there are some others who asked about it before, just search up "loading screen" or something along those lines in the issues tab and you'll find some stuff.

**Comment by HiroMizuki** [comment]
#1728
