### ISSUE TITLE
Adding new mainmenu buttons through Lua

### ISSUE THREAD

**Issue by Trenton0** [ShadowMario/FNF-PsychEngine#2314]
### What feature do you want to get added on the base engine?

The title speaks for itself, You can add menu buttons through lua files (Example: Let's say i want to add a twitter button on the mainmenu that takes you to the mod creator's twitter i would put the .lua in Mods/Mainmenu and put the png file in images/mainmenu then restart the game and it would appear and function how it was intended)

**Comment by tposejank** [comment]
no. the softcoded credits are for that.

**Comment by KutikiPlayz** [comment]
I don't think this would be good especially since basically the whole purpose of making mods with Lua, besides not having to mess with the source, is to be able to have all your mods in one game. Messing with the main menu would most likely bring issues when it comes to compatibility with other mods. As tposejank said, just use credits for that.
