### ISSUE TITLE
How to remove notes from other grid

### ISSUE THREAD

**Issue by lemz1** [ShadowMario/FNF-PsychEngine#2479]
### What is your question?

Hi,
I am not sure how to describe it but I'll try.
So I increased the size of the grid where you place notes and I am able to place notes, but I am not able to delete them by clicking on them. (It deletes the notes when I use clear Section)
I also noticed when placing a note on dad's side the note on the right grid also light up but I am not sure if this has something to do with it.
Windows 64bit version 0.5

Here's a Video
![ezgif com-gif-maker](https://user-images.githubusercontent.com/87707926/147005871-02128208-e4f2-4015-ab72-d4d22231209d.gif)

**Comment by KutikiPlayz** [comment]
There's probably some code that you gotta change to make it so that you can delete notes in other areas. This same thing happens when you port over the expurgation chart for example, since the way they made the halo notes is that they placed normal notes off the grid and then the game changed them to halo notes, but you can't remove them by clicking.

I'll take a look and see if I can find anything, I'll need it anyway. Manually going into the chart file and deleting extra notes one by one is a pain in the ass.

**Comment by 4wdthinks** [comment]
from what i see, the code checks if the mouse is overlapping a note and waits for a key press, but it doesn't say mention the grid at all.

**Comment by 4wdthinks** [comment]
update: might've found something? 
![image](https://user-images.githubusercontent.com/79160331/147106832-f0d1443f-88a9-462d-bbb8-2069ca7fbe25.png)

**Comment by KutikiPlayz** [comment]
> update: might've found something? ![image](https://user-images.githubusercontent.com/79160331/147106832-f0d1443f-88a9-462d-bbb8-2069ca7fbe25.png)

That code seems to just be the white square under your mouse that shows where you'll place a note.
I did some experimenting and saw that GRID_SIZE equals 40, so I changed it to 80 to see what would happen and that made the white square snap to every other space on the grid. I'm assuming lemz1 already changed that value so that they can place notes on the other strum, I still don't know why you can't delete them.

**Comment by KutikiPlayz** [comment]
Hey, @lemz1 do me a favor real quick and place a note on the extra strum and the strum next to it in the same spot. Click on the note in the extra strum, does it delete the other note in the other strum?

I can see in the gif you sent that selecting a note in the strum closest to that one selects the notes in the other strum, but won't delete them.

**Comment by KutikiPlayz** [comment]
I think I know what the problem is.
As you can see in these screenshots neither the select note function nor the delete note function uses GRID_SIZE for anything  
![Screenshot (1006)](https://user-images.githubusercontent.com/73810550/147137664-dfe7981b-f780-4b3e-bd52-f4457c56701e.png)
![Screenshot (1004)](https://user-images.githubusercontent.com/73810550/147137672-ee894eff-e14a-4039-bcb1-8fb995e6e7c2.png)
While the add note function does   
![Screenshot (1005)](https://user-images.githubusercontent.com/73810550/147137703-9a99238c-f43b-4117-9bed-ff181e1acc2e.png)
There seems to be some other variable used in the select note and delete note functions that tell the grid size, just gotta figure out what that variable is.

**Comment by KutikiPlayz** [comment]
Oh and btw if you make the game trace something the command prompt when you delete a note it'll trace whatever you said, but won't delete the note.

**Comment by lemz1** [comment]
> Hey, @lemz1 do me a favor real quick and place a note on the extra strum and the strum next to it in the same spot. Click on the note in the extra strum, does it delete the other note in the other strum?
> 
> I can see in the gif you sent that selecting a note in the strum closest to that one selects the notes in the other strum, but won't delete them.

Hi, I tested it and it does delete the other notes (only right side)
Here's a gif
![ezgif com-gif-maker(2)](https://user-images.githubusercontent.com/87707926/147141172-970f8372-f553-4f16-bde1-8ccb9297c5fc.gif)

> Oh and btw if you make the game trace something the command prompt when you delete a note it'll trace whatever you said, but won't delete the note if it isn't on the default grid.

It traces the message even though the note isn't deleted
Who would have suspected, another gif. Cool
![ezgif com-gif-maker(3)](https://user-images.githubusercontent.com/87707926/147141913-a067484e-141d-4f44-afca-1c2e0189db2a.gif)

**Comment by ShadowMario** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/44785097/147263980-07541594-70be-45c3-8952-91dae841c03c.png)
You have to add a check for the third grid's notes and make it add +8 to the note data.
