### ISSUE TITLE
getProperty can't get storyDifficulty variable using Lua

### ISSUE THREAD

**Issue by NS-Unfair** [ShadowMario/FNF-PsychEngine#2575]
### Describe your bug here.

I was making modcharting a mod made in Psych Engine and came across a bug in the getProperty function. When I tried to print `getProperty('storyDifficulty')`, it printed `storyDifficulty`, which isn't supposed to happen. The same thing occurs on Psych Engine 0.5.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I have made no changes to the build

**Comment by Starmapo** [comment]
'storyDifficulty' is a static variable, which means it's the same across all instances of PlayState. Due to this, you can't get it from one specific instance, you have to get it from the class ('PlayState' in this situation). Using:
`getPropertyFromClass('PlayState', 'storyDifficulty')`
(should return a number)

**Comment by ShadowMario** [comment]
You can also use `difficulty` local lua variable for getting the difficulty number.

**Comment by ShadowMario** [comment]
Check Lua Script API's "Variables" page for more info.

**Comment by NS-Unfair** [comment]
Oh, okay, I misunderstood. I thought I could get the variable by just using getProperty.
