### ISSUE TITLE
How to make a note get not deleted when a different note is pressed

### ISSUE THREAD

**Issue by lemz1** [ShadowMario/FNF-PsychEngine#2617]
### What is your question?

Hi,
sorry for that shitty title.
I managed to implement the deletion of the notes on the other grid after ShadowMario's advice, but one problem still exists.
The problem is that when 2 same notes (for example. 2 up arrows), one on the second grid and the other on the third grid, are placed, and then trying to delete the note on the third grid, leads to the note on the second grid to be deleted.

Here's a gif for demonstration purposes:
![ezgif com-gif-maker(4)](https://user-images.githubusercontent.com/87707926/147299152-9300f177-1283-4ee7-82fe-6977c163db51.gif)

Here's the code (sorry if it's trash)
![Unbenannt](https://user-images.githubusercontent.com/87707926/147299221-949582e5-4832-45d7-a600-0a0d8003b02d.PNG)

previous issue #2479

**Comment by Ashura09** [comment]
### ** MAYBE THIS IS INCORRECT **
Looks like its something to do with **_noteDataToCheck += 4_**
try to delete that if statement.
Explanation:
FNF handles notes using integers, so left is 0 
down is 1
up is 2 
right is 3
and they use + 4 to delete same note, because right side in charter is left side but + 4.
And if you delete statement with +=4 it won't check for other side.

**Comment by lemz1** [comment]
Hi it didn't work but I came up with a different solution. I just made an if statement that checks if a specific key is pressed and if it is pressed you can delete the note on the second or third grid
