### ISSUE TITLE
start countdown when song start

### ISSUE THREAD

**Issue by AlyssonRo** [ShadowMario/FNF-PsychEngine#3165]
### What is your question?

there is a way to make the countdown start when the inst and voices start in lua ?

**Comment by 4wdthinks** [comment]
uhhh what?

**Comment by PDL2CGamejolt** [comment]
> uhhh what?

I think he meant like make the countdown start when the song starts, like in Opheebop

**Comment by i-winxd** [comment]
This is speculation because I didn't try this yet.
Set ``skipCountdown`` to true immediately (on ``onCreate``).
Code in the ready, set, go!! in the lua yourself referencing the source code. That is located in line 1666 of source so you'll have to convert that to lua yourself. Note that how long ready, set, gos last on screen are tied to the BPM of the song.
