### ISSUE TITLE
Get rid of resolution thing

### ISSUE THREAD

**Issue by Doritojoey** [ShadowMario/FNF-PsychEngine#3321]
### Describe your bug here.

The resolution option breaks more than it benefits and its completely pointless, just do this
PsychEngine.exe > Properties > Compatibility > Change high DPI settings > Check both the things
Full resolution without window breaks
And a bug I got was mainly with the charting, the grid was misplaced

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by Doritojoey** [comment]
On linux, this problem basically doesn't exist, from what I tested Psych on (Manjaro linux plasma) it seems to boot in full res automatically

**Comment by ShadowMario** [comment]
The 4:3 resolution support is there because some people experienced issues on 16:9 that prevented them from playing the engine.

**Comment by skedgyedgy** [comment]
-- i'd say that's okay but the way it was implemented is genuinely really bad and doesn't improve the engine in the slightest, especially since now it restricts the engine to three resolutions god forbid someone wants to play windowed maximized or make the window smaller. what are some of these issues in 16:9?

**Comment by Doritojoey** [comment]
They've fixed the bug it seems like. I guess it works

**Comment by skedgyedgy** [comment]
-- it was me i did it i fixed it
