### ISSUE TITLE
zoom bug

### ISSUE THREAD

**Issue by predo2810** [ShadowMario/FNF-PsychEngine#3375]
### Describe your bug here.

uhh, i don't know if it's a bug but, when the opponent hits a note, the screen zoom in to the center, I CAN'T SEE THE NOTES/MISSES/SCORE/ETC ;-; ;-; ;-;
![2022-01-09](https://user-images.githubusercontent.com/93801931/148697493-06eb20f3-585f-4400-8ce4-147823c740f8.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, like, CreditsState.hx, PlayState.hx, MainMenuState.hx, StoryMenuState.hx, TitleState.hx and CoolUtil a little...

**Comment by NotHyper-474** [comment]
Do you have a 4:3 display? I have the same issue and I've noticed it's because of that.

**Comment by bbpanzu** [comment]
repull the source code. there's a feature in the options to edit how the game scales based on resolution. set it to ADAPTIVE or letterbox

**Comment by predo2810** [comment]
> Do you have a 4:3 display? I have the same issue and I've noticed it's because of that.

i don't know... like, probably no.

**Comment by predo2810** [comment]
> repull the source code. there's a feature in the options to edit how the game scales based on resolution. set it to ADAPTIVE or letterbox

where is it? in the options folder on the source? i don't found nothing
![Captura de tela 2022-01-10 143723](https://user-images.githubusercontent.com/93801931/148812274-482e9dcf-74b9-49ea-9ca7-2b10d8c688ff.png)

**Comment by kitinho** [comment]
i have this same problem but i haven't edited any source code files.
all versions of this engine and another engines too.
my default resolution is 1152x864 with one monitor. when i put a high resolution this problem fixes, or take another monitor (2 monitor using)

i sure this problem is for a lot people, soo, this mode of adaptive can be a default option to this engine? to anyone have this problem?
why the engine make this bug?
how it works
