### ISSUE TITLE
Help with lua buttons

### ISSUE THREAD

**Issue by main-thing** [ShadowMario/FNF-PsychEngine#4237]
### Describe your problem here.

I want to add a button via lus that pops up on screen. When its clicked it will set a variable to 1 and when released back to 0. How do I do this? ( i know it is possible but Im too stupid to remake it in lua. )

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope. Just a pre-builded version.

**Comment by blueDev2** [comment]
So this is a bit roundabout since we are restricted by Lua functions
The following should be placed in create():
Since you cannot make a FlxButton using Luas, you have to make an animated sprite for the button by making a spritesheet and using an XML. [Look Here](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Custom-Sprites-Functions)
Make your animations for the button and play the idle animation looped [Look Here](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Object-Functions#animations-functions)
The following should be placed in update():
During each update, poll for the position and size of the button and the location of the mouse and check if they overlap. Also, check if the mouse is left clicked[See here](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-General-Functions#mouse-click-functions)
If the previous condition was met, change the animation of the button and set whatever variable you wanted to set here.
Also, add an "else" clause to reset the button animation and the variable.

**Comment by main-thing** [comment]
Thanks, I'll see if I can make a script that makes it easier to find the positions. Like a premade calculator.
