### ISSUE TITLE
a suggestion + question

### ISSUE THREAD

**Issue by trayfellow** [ShadowMario/FNF-PsychEngine#49]
im probably gonna sound like an idiot rn but here goes

suggestion : make freeplay songs only read from the freeplaysonglist.txt instead of weekdata.hx so we have more customizability for the freeplay songs

question : can you guys add compability for mac and linux? fueg0 managed to compile psych engine for mac but he was only able to play week 4 cause the other stages just ended up crashing for him

**Comment by ShadowMario** [comment]
Songs will be loaded in week .json files as of 0.4 because of the in-game Week Editor.
I can't add compatibility to Mac myself because of how Haxe apparently requires me to have a Mac PC to compile it to Mac, not sure about Linux though.

![](https://user-images.githubusercontent.com/44785097/132952239-2acca56f-818e-4eaf-8f1c-b0fd0d64dc96.png)
