### ISSUE TITLE
Intro text

### ISSUE THREAD

**Issue by xDItsTej** [ShadowMario/FNF-PsychEngine#5424]
### Describe your problem here.

I'm wondering.. Is there a way I can make the intro text from "Friday Night Funkin" say something else? (And also the "Not associated with newgrounds" text)
![image](https://user-images.githubusercontent.com/97074458/154851005-b22b94f1-cba0-4988-a173-8ecf45e62b5e.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Not anything that affects this.

**Comment by frantastic24** [comment]
TitleState.hx
Line 583 to 615

**Comment by xDItsTej** [comment]
How do I get there?

**Comment by frantastic24** [comment]
Inside the source folder

**Comment by xDItsTej** [comment]
Alright, well I'm here. I don't know how to get to the source folder. 
![image](https://user-images.githubusercontent.com/97074458/154854791-6677b0a7-9195-46c1-80e0-1f306596391e.png)

**Comment by frantastic24** [comment]
There is no source folder because you're not using source even though you put source here:
![Screenshot_2022-02-20-14-11-55-896.jpg](https://user-images.githubusercontent.com/95725102/154855025-aee41ca7-e437-400c-8392-2f261198012e.jpg)
You'll have to get the source code and edit it yourself, there's plenty of guides on how to do this online

**Comment by xDItsTej** [comment]
Alright. Thanks for the help.
