### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Gui-iago** [ShadowMario/FNF-PsychEngine#60]
(for reference, https://github.com/KadeDev/Kade-Engine )
would be cool to have a "Colors by Quantization" toggle on the options menu, it's nothing really that big, but the arrow colors following the beat snapping of the songs is just cool, and maybe even useful for some specific charts

would also be cool to have an option to change scroll speed just like K.E does

**Comment by Yoshubs** [comment]
KE quants are pretty eh

**Comment by Yoshubs** [comment]
I'm not shadowmario but personally quantitization doesn't really fit into psych engine because of the note recoloring as well as some other things, quants need to be at least 6 colors to be considered quants for example and having 6 colors for switching would be pretty weird, it could be like a color preset but even then psych engine isn't really trying to be a competitive engine its trying to be its own ease of access modding engine 

also, suggesting ideas directly is good, but suggesting features from someone else's project is probably not the best idea

especially when they accuse you of stealing already

but uh, that's just my opinion really

**Comment by ShadowMario** [comment]
Shubs said perfectly.
Scroll speed will be added once i fix the shit code on Options menu, as i've stated multiple times already.
There's already a PR for this on hold.

**Comment by Pairos13** [comment]
Fuck Shit Crap
