### ISSUE TITLE
Charting editors load null difficulty

### ISSUE THREAD

**Issue by Reycko** [ShadowMario/FNF-PsychEngine#6609]
### Describe your bug here.

so if you don't insert a null difficulty to your data song file, it crashes when debug key is pressed
(source & lua)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Theoyeah** [comment]
Update to psych 0.5.2h bc it is fixed

**Comment by Pika-Art** [comment]
> Update to psych 0.5.2h bc it is fixed

It isn't-

**Comment by ShadowMario** [comment]
Couldn't replicate the bug, record a video.

**Comment by frantastic24** [comment]
From what I understand the chart editor in the main menu loads normal difficulty, so if you switch to another song that doesn't have it you get the usual "chart json doesn't exist" error

**Comment by cherryiguess** [comment]
this happens because you never loaded in a difficulty when accessing through the chart editor instead of the song, which is why this happens since it takes the recent difficulty played on

**Comment by mayo78** [comment]
they are talking about this:
![image](https://user-images.githubusercontent.com/75394229/157560940-56210c6e-7cec-4b6c-9349-bd2fa32283b2.png)

(happens when psych engine hasn't loaded in a song in that current session)

**Comment by TBiscuit1** [comment]
Ok I figured what is the bug, it will try to load the latest difficulty that was loaded in, when the game start, the editor difficulty is null but when you load test, the actual chart is on normal, so the game seach for a null difficulty which doesn't exist, this bug will also happen if you are on a chart with a custom difficulty and then go to another song using the Reload Json button

To make it shorter, the internal difficulty is "normal" while the editor difficulty is null, causing a crash when trying to load any song (even itself)

I do wonder, why doesn't it check if the song even EXIST before trying to go in it... crashing the game because of a spelling mistake/wrong difficulty is so annoying

**Comment by TBiscuit1** [comment]
I am not sure of myself but this line might be at cause (in CoolUtils)
![image](https://user-images.githubusercontent.com/53101126/157958468-74c7c885-defd-45d2-93bd-098fca059223.png)

Maybe because Test isn't in a story week, it cannot reach a difficulty and so the array is empty, it just sends out a null which then cause the game to crash since no song have a null difficulty, only a theory tho

**Comment by tylerandari12** [comment]
If you have no way to acces source code to fix this, adding a null difficulty while working does solve the problem temporarily.
