### ISSUE TITLE
all arrows are the left arrow

### ISSUE THREAD

**Issue by ByronisJoan** [ShadowMario/FNF-PsychEngine#671]
### Bug report

When i build the game the arrows are left arrow and the hold arrow is scaled high like its edited and when the hold notes appear, the game crashes

### Did you edit anything? If so, mention or summarize your changes.

game crash

**Comment by MeowcaTheoRange** [comment]
This has happened to me when making my [Guitar Hero](https://twitter.com/THEO3527/status/1454097140255444995?s=20) arrows. Build on `-debug`, (if you're on Source), and check the logs. Check the XML to make sure everything's named correctly (The Left arrow is Purple, which is the arrow that confuses most, due to a misspelling in the files.)

**Comment by ByronisJoan** [comment]
thank you
