### ISSUE TITLE
Many things I think would make Psych Engine a bit better.

### ISSUE THREAD

**Issue by PrismLight** [ShadowMario/FNF-PsychEngine#7081]
### What feature do you want to get added on the **base** engine?

- Option to change the volume of Hitsounds in the Chart Editor
- A system in the PauseSubState that play the 3, 2, 1, Go countdown before resuming the song again.
- A system for custom notes to have their own pixel style for the ```isPixelState``` variable. (add -PIXEL at the end of a notetype)
- An editor for TitleState if you feel lazy editing the JSON file. (IM NOT REQUESTING STAGE EDITOR)

That's pretty much all I could think of. I'm trying to code this as well but I hope the team looks into this.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/44785097/158714416-3e289588-75bb-4a18-b488-3db49e681bec.png)
ARE YOU SERIOUS????

Also i'm not gonna do an editor for the title screen, doing editors is absolutely time consuming and i won't do an editor for every little thing just because you don't feel like you want to work on your mod

**Comment by PrismLight** [comment]
They were just ideas. Bruh.
