### ISSUE TITLE
New editors request!

### ISSUE THREAD

**Issue by MarioGuyWasTaken** [ShadowMario/FNF-PsychEngine#736]
### What feature do you want to get added on the base engine?

A video editor! Let's you change the x and y position of the cutscene, It lets you import a .mp4 file and also export the code, If the video is not 720p, it automatically converts it to 720p. Maybe even a 3 2 1 editor? I mean when it counts down and starts the song, Maybe even a credits editor and start screen intro editor?

Sorry, I'm asking to many requests, Please forgive me lmao.

**Comment by ShadowMario** [comment]
No.

**Comment by MeowcaTheoRange** [comment]
I mean, does `haxelib` support `ffmpeg` or have some kind of port of it? If so, then this Issue could probably just be reduced to "convert bigger video down to 720p and crop instead of crash"

A `CreditsState` editor, no, that would be kind of ridiculous. You can just go into the source and edit it yourself, it's relatively simple. Plus, if we're talking about Lua mods, those are more modular to a main Psych Engine package than their own thing, so it'd be more appropriate to have a video of the credits after you've played (refer to thing I said above)

Start screen intro editor? Can't you just go to introText.txt and do that yourself? Even with adding new parts to the thing before the random text, you can just... y'know. Go into the source and change that. In Lua mods, same thing as before.
