### ISSUE TITLE
Character-Specific Dialogue sound

### ISSUE THREAD

**Issue by GWRRailway** [ShadowMario/FNF-PsychEngine#7607]
### What is your question?

in Psych Engine 0.5.2h, a new feature was added where you can import custom dialogue sounds, but how do I set it to a specific character?
(Example: If I want Bf to talk, Bf's dialogue sound plays, when the text switches to gf, it switches to a gf dialogue sound.)

**Comment by MaybeMaru** [comment]
in the .json of the dialogue in every line of dialogue there is a line called `"sound": "yoursound",` just add in the place where "yoursound" is the name of your sound stored in the mods/sounds folder.
I had to do this manually in a text editor because the ingame editor is kinda glitchy, but you should be able to make it ingame too
