### ISSUE TITLE
Bf Tweening

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#7878]
### Describe your bug here.

I am not sure why, but it seems, that you can't use doTweenX and doTweenY on Boyfriend.
It doesn't matter if I enter bf in there. I just doesn't work for some reason.

I made an own stage for it and copied something in I got somewhere. It lets things float/hover.
It works with everything. Dad, GF, and even Stage elements. But it does not work on BF for some reason.

I'll just paste the bit of code in here:

`function onUpdate(elapsed)
	songPos = getSongPosition()

local currentBeat = (songPos/5000)*(curBpm/60)

	doTweenY('gfmove', 'gf', -100 - 150*math.sin((currentBeat+12*12)*math.pi), 1)
	doTweenX('disruptor3', 'disruptor.scale', 0 - 50*math.sin((currentBeat+1*0.1)*math.pi), 3)
	doTweenY('disruptor3', 'disruptor.scale', 0 - 31*math.sin((currentBeat+1*1)*math.pi), 8)

	doTweenY('opponentmove', 'dad', -100 - 150*math.sin((currentBeat+12*12)*math.pi), 1)
	doTweenX('disruptor2', 'disruptor.scale', 0 - 50*math.sin((currentBeat+1*0.1)*math.pi), 3)
	doTweenY('disruptor2', 'disruptor.scale', 0 - 31*math.sin((currentBeat+1*1)*math.pi), 8)

	doTweenY('bfmove', 'bf', -100 - 150*math.sin((currentBeat+12*12)*math.pi), 1)
	doTweenX('disruptor1', 'disruptor.scale', 0 - 50*math.sin((currentBeat+1*0.1)*math.pi), 3)
	doTweenY('disruptor1', 'disruptor.scale', 0 - 31*math.sin((currentBeat+1*1)*math.pi), 8)

	doTweenY('stagemove', 'stagefront', -100 - 150*math.sin((currentBeat+12*12)*math.pi), 1)
	doTweenX('disruptors', 'disruptor.scale', 0 - 50*math.sin((currentBeat+1*0.1)*math.pi), 3)
	doTweenY('disruptors', 'disruptor.scale', 0 - 31*math.sin((currentBeat+1*1)*math.pi), 8)

end`

But if this is just an issue by me, thenit would be cool, if it could get fixed

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I made a stage in lua, to let things float

**Comment by im557** [comment]
rename 'bf' to 'boyfriend'.

**Comment by ZeitHeld** [comment]
> rename 'bf' to 'boyfriend'.

won't do

**Comment by keanu64github** [comment]
thats how you fix it though

**Comment by amogusgame** [comment]
heres the fixed code:
`doTweenY('gfmove', 'gf', -100 - 150*math.sin((currentBeat+12*12)*math.pi), 1)
doTweenX('disruptor3', 'disruptor.scale', 0 - 50*math.sin((currentBeat+1*0.1)*math.pi), 3)
doTweenY('disruptor3', 'disruptor.scale', 0 - 31*math.sin((currentBeat+1*1)*math.pi), 8)

doTweenY('opponentmove', 'dad', -100 - 150*math.sin((currentBeat+12*12)*math.pi), 1)
doTweenX('disruptor2', 'disruptor.scale', 0 - 50*math.sin((currentBeat+1*0.1)*math.pi), 3)
doTweenY('disruptor2', 'disruptor.scale', 0 - 31*math.sin((currentBeat+1*1)*math.pi), 8)

doTweenY('bfmove', 'boyfriend', -100 - 150*math.sin((currentBeat+12*12)*math.pi), 1)
doTweenX('disruptor1', 'disruptor.scale', 0 - 50*math.sin((currentBeat+1*0.1)*math.pi), 3)
doTweenY('disruptor1', 'disruptor.scale', 0 - 31*math.sin((currentBeat+1*1)*math.pi), 8)

doTweenY('stagemove', 'stagefront', -100 - 150*math.sin((currentBeat+12*12)*math.pi), 1)
doTweenX('disruptors', 'disruptor.scale', 0 - 50*math.sin((currentBeat+1*0.1)*math.pi), 3)
doTweenY('disruptors', 'disruptor.scale', 0 - 31*math.sin((currentBeat+1*1)*math.pi), 8)`
because theres no 'bf' callback exist in source code check urself

**Comment by amogusgame** [comment]
the thing after the string of ur object character its the callback or name for object/boyfriend character or opponent character

**Comment by ZeitHeld** [comment]
omg, I saw the issue. thanks for helping out with it.
I just pasted it at the wrong place.
