### ISSUE TITLE
Make notes appear and disappear

### ISSUE THREAD

**Issue by Bruno215Brochado** [ShadowMario/FNF-PsychEngine#796]
### Describe your problem here.

I want to make the notes appear and disappear like Termination from QT mod but idk how to make it.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

**Comment by Micasddsa** [comment]
Most likely you need to mod from source to do that.
Don't think it's possible using lua.

**Comment by nicho01022** [comment]
Yeah U need to do it from source

**Comment by SrtHero278** [comment]
You can just use noteTweenAlpha(tag:String, note:Int, value:Dynamic, duration:Float, ease:String)

**Comment by lolbruhfart** [comment]
No you can shake the screen with events like this 1, 99.99

**Comment by drakonieyah** [comment]
> You can just use noteTweenAlpha(tag:String, note:Int, value:Dynamic, duration:Float, ease:String) in a script in your song folder

This

**Comment by Real-Pog** [comment]
> > You can just use noteTweenAlpha(tag:String, note:Int, value:Dynamic, duration:Float, ease:String) in a script in your song folder
> 
> This

it does not work

**Comment by NS-Unfair** [comment]
I think what's happening is Real-Pog is copying "noteTweenAlpha(tag:String, note:Int, value:Dynamic, duration:Float, ease:String)" into the lua script and that doesn't work.

If you want to hide the left side's arrows, you can copy & paste this into your Lua script:
`
function onUpdate(elapsed)
 -- This is how I do it
 -- Alpha is +16
 -- X is +0
 -- Y is +8
 -- Angle is +24

  -- Opponent arrows: 0-3
  -- Player arrows: 4-7
  -- hide and show the opponents arrows
   for i=0,3 do
     -- Alpha is 0-1 (0 being invisible)
     noteTweenAlpha(i+16, i, math.floor(curStep/12), 0.3)
  end
end
`

Basically, the arrows are indexed 0-7 (0-3 being the Opponent's arrows)
So if you want to hide the left most arrow you can do this:
`
 noteTweenAlpha(0+16, 0, 0, 0.0001)
`

The third value (value) is the alpha. If you want to do alpha 0-255 instead of 0-1, this is what you could pass:
`
[number]/255
`

The fourth value (duration) is what it sounds like.

For the final value (ease,) you can go to https://api.haxeflixel.com/flixel/tweens/FlxEase.html and find which easing you would like to use. For example, if you want quadIn easing, you can do this:
`
 noteTweenAlpha(0+16, 0, 0.6, 2, 'quadIn')
`

If you are new to Lua, you can go to Lua.org
Also, you can go to the Lua Scripting [wiki](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API) for more info.

**Comment by perngjiafu** [comment]
isnt termination from lua chart?

**Comment by SrtHero278** [comment]
> isnt termination from lua chart?

Yes.
