### ISSUE TITLE
does anyone have a script that  randomly changes noteskin out of nowhere like dave and bambi?

### ISSUE THREAD

**Issue by SquareCatALT** [ShadowMario/FNF-PsychEngine#8072]
### What is your question?

m

**Comment by Draconic-Hybrid** [comment]
[noteskinchange.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8460242/noteskinchange.zip)

Two things first.
1) These are not mine.
2) It visually takes a second or so after the event is triggered to have both the notes fully change, due to the notes that were already loaded before the event trigger.
