### ISSUE TITLE
Does anyone know why Psych Engine has an assets/data/smash.json?

### ISSUE THREAD

**Issue by RowanSkie** [ShadowMario/FNF-PsychEngine#8187]
### What is your question?

I just saw this on another Psych Engine-based mod that just decided to bundle their mod with Psych Engine and checked my own 0.5.2h copy.

There's no song though, and the app crashes with a missing smash-null.json file error.

What is it?

**Comment by HiroMizuki** [comment]
1st - The chart is from vanilla, and it was explained here: https://twitter.com/ninja_muffin99/status/1348708168138969091?s=20&t=INsg1hpxFznWNM_XYvc7YA

2nd - The null error is a bug cuz Psych has been shitcoded these days (maybe it'll be fixed)

3rd - Yes, the song doesn't exist because, by what I've seen, the song that would be used was a test, the song is from SSMB, Break The Targets OST (https://youtu.be/Vc1wzDWFvf8)

**Comment by ShadowMario** [comment]
It's a chart Ninjamuffin made to test if the chart system worked as far as i know.
I've recharted it but removed the song because i thought it would be fun (And had to remove it because the song is copyrighted).

Link to the audio: https://www.youtube.com/watch?v=4rK0t4tScxc
