### ISSUE TITLE
how to code achievements in 0.5.2h

### ISSUE THREAD

**Issue by bf244** [ShadowMario/FNF-PsychEngine#8203]
### Describe your problem here.

how to code achievements in 0.5.2h 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by zeadd21g1233** [comment]
what achivement you want
no miss achivement
beat crazy diffculity
i know how to add achivement
to 0.5.2h

**Comment by antoSKRLOL** [comment]
it's easy lol


first you go to achievements.hx and add the name of your achievement and shit it will do, you go to line 153 [or it depends on how much you modify] you add the achievements you put

example: if you put 3 achievements

instead of it being Achievements.achievementsStuff[id][0], 16);

be
Achievements.achievementsStuff[id][0], 19);

then you go to the play state in line 3180 you put the name of your achievement

and then on line 4451

you edit the if(isStoryMode && campaignMisses + songMisses < 1 && CoolUtil.difficultyString() == 'HARD' && storyPlaylist.length <= 1 && !changedDifficulty && !usedPractice)

and you put the name of your difficulty

example:

if(isStoryMode && campaignMisses + songMisses < 1 && CoolUtil.difficultyString() == 'CRAZY' && storyPlaylist.length <= 1 && !changedDifficulty && !usedPractice)

**Comment by antoSKRLOL** [comment]
If I'm wrong about something, correct me or tell me if something doesn't seem to you and I'll help you

**Comment by bf244** [comment]
beat a week and get the achievement
