### ISSUE TITLE
Adding more then one event to Roses

### ISSUE THREAD

**Issue by Aden-Mystio** [ShadowMario/FNF-PsychEngine#8277]
### Describe your problem here.

I would like to know If I can add more than one event to roses. I would like to add a screenshake event

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

idk what to put here

**Comment by Lorekeeper49** [comment]
It's simple, just go into the chart editor for roses and add the events, make sure you click 'load events' first though as the events might be a separate json in the data so the events play on every difficulty.  Once you're done, click 'save events' and save that json into the data folder for the song (making sure not to change the name otherwise it won't work) and save it in there replacing the file that's already there
