### ISSUE TITLE
Add Character Custom Event

### ISSUE THREAD

**Issue by Lorekeeper49** [ShadowMario/FNF-PsychEngine#8342]
### Describe your problem here.

Please note that I'm doing this on 0.5.2h
https://drive.google.com/file/d/1pV3AJGj59D9sdCVd7x3ElN_Gd8Wb4tXE/view?usp=sharing

Here's the scripts so you can debug them:
[Add KOU.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/8559401/Add.KOU.txt)
[KOU.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/8559406/KOU.txt)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
`luaSpriteAddAnimationByPrefix` is missing a capital A in "add", so no animations were added to the sprite
![image](https://user-images.githubusercontent.com/95725102/165211653-ce8f15b6-ba2a-4b20-ae5a-ab408aadde93.png)
the function is also deprecated so i recommend using addAnimationByPrefix since it's also shorter
