### ISSUE TITLE
Hurt note hitbox is excessively big (or maybe its easier to hit then normal notes) (change a feature, not add one)

### ISSUE THREAD

**Issue by Beginner-codi** [ShadowMario/FNF-PsychEngine#8351]
### What feature do you want to get added on the **base** engine?

An exemple of this problem fixed is PsychEngine-Extra by Starmapo, its easier to hit notes on songs that are filled with hurt notes, like kaboom from Madness Vandalization (i edited the chart to make every note a double).

hopefully this is not troublesome

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment]
I don't think there are plans to make softcoded hit timings (#2014), but `earlyHitMult` is a thing, you can also write your own timing formula with Lua

**Comment by KutikiPlayz** [comment]
> I don't think there are plans to make softcoded hit timings (#2014), but `earlyHitMult` is a thing, you can also write your own timing formula with Lua

the only issue with that is that there's no lateHitMult, which is really unfortunate (and also really easy to add) since the biggest issue with mines is that people will hit them accidentally due to the late timing a lot more than hitting them early
they don't need to change the hurt notes, just add the option to change both hit times so that people can change the hurt notes themselves or fix issues with custom notes as well (since some custom notes have a fire trail for example so you would want to lower the late hit multiplier so that you can actually hit other notes behind them)

**Comment by Beginner-codi** [comment]
ok, thanks

Em qua., 27 de abr. de 2022 às 11:19, frantastic24 ***@***.***>
escreveu:
