### ISSUE TITLE
why does the game crashes when i press singDOWN-alt on the ghost animations

### ISSUE THREAD

**Issue by perngjiafu** [ShadowMario/FNF-PsychEngine#8356]
### Describe your bug here.

:/

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Draconic-Hybrid** [comment]
If it's because it's an animation you added, then you've got to save the character and reload them. It's weird, but ghost animations use the animation list of the last saved version of that character. This could also be the reason why if you reorder the animations and click one of them, you'll get a different one. Just remember to save and reload first.
