### ISSUE TITLE
how do i make a scrolling background with lua

### ISSUE THREAD

**Issue by apleGitHub** [ShadowMario/FNF-PsychEngine#8418]
### Describe your problem here.

i want to make my background infinitely scroll and loop with lua. how do i do that?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Grape-Boy** [comment]
You need to create a background sprite, then make an identical one positioned at the end of the first sprite, then you tween the two sprites together at the same time.
When the sprites finish moving, you reset the positions of the sprites and tween them again so that it loops.

You can use this script :
```lua

local width = 0
local spriteName = "limoSunset" -- replace limoSunset with the name of your sprite

function onCreate()
	makeLuaSprite("bg1", "limoSunset", 0, 0)
	width = getProperty("bg1.width")
	
	makeLuaSprite("bg2", "limoSunset", width-20, 0)
	
	addLuaSprite("bg1", false)
	addLuaSprite("bg2", false)
	
	doTweenX("bg1Tween", "bg1", -width, 5, "linear")
	doTweenX("bg2Tween", "bg2", -20, 5, "linear")
end

function onTweenCompleted(tag)
	if tag == "bg1Tween" then
		setProperty("bg1.x", 0)
		setProperty("bg2.x", width-20)
		
		doTweenX("bg1Tween", "bg1", -width, 5, "linear")
		doTweenX("bg2Tween", "bg2", -20, 5, "linear")
	end
end

```

I used this image :

![limoSunset](https://user-images.githubusercontent.com/96194070/166240509-d707e14d-8d4a-49ae-8607-ac153ab2ac61.png)
