### ISSUE TITLE
Transitions like indie cross (Source Code)

### ISSUE THREAD

**Issue by EnzoMunizz0** [ShadowMario/FNF-PsychEngine#8537]
### Describe your problem here.

I wanted to know how to make a tile transition, like indie cross, but I tried in many ways and I couldn't

### Are you modding a build from source or with Lua?

Source Code

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I haven't edited anything so far

**Comment by voxovistired** [comment]
Since I don't really like to spoonfeed people the code, I'll just provide some links that will be helpful for you (Most likely):
Use this for the transition.
https://api.haxeflixel.com/flixel/addons/transition/FlxTransitionableState.html
Use the TILES transition type.
https://api.haxeflixel.com/flixel/addons/transition/TransitionType.html
And use this.
https://api.haxeflixel.com/flixel/addons/transition/GraphicTransTileSquare.html

Hope this helps!

**Comment by EnzoMunizz0** [comment]
Thanks a lot, I'll see if it works, but thanks for helping me!!!!

**Comment by WolfyTail** [comment]
@EnzoMunizz0 I figured out that in **TitleState.hx** there's an unused code for a fading transition _(look at the picture)_. Change "FADE" by "TILES" and that's it (in line 24 you'll found this: **import flixel.graphics.FlxGraphic;**. Delete the "//").

Then, go to **MusicBeatState.hx** and delete all the lines that are related to **CustomFadeTransition** (the old transition). Once you're done, export the game and _voilà_. ;)
_________
![image](https://user-images.githubusercontent.com/95707370/192094209-73da9a28-e5bb-4573-9e01-00ddcec021eb.png)
