### ISSUE TITLE
How do i add a warning image to psych engine.

### ISSUE THREAD

**Issue by JacksRobotics** [ShadowMario/FNF-PsychEngine#8815]
### What is your question?

i want to add this warning after you open the game
![grunkywarning](https://user-images.githubusercontent.com/100966392/170818218-ca1ac81d-6aec-483e-8d1b-493f84d18985.png)

**Comment by PrismLight** [comment]
I'm guessing source. Also please add gore to da mod.

Find this line.
https://github.com/ShadowMario/FNF-PsychEngine/blob/b6c64fcf3039ddc2252ee9bb4c5adc67d26d4345/source/TitleState.hx#L452-L457

Force it to go to another state that you made. Like, lets make up the name: WarningState.hx
Make that new file and you can sorta just copy the whole code from [FlashingState.hx](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/FlashingState.hx)

Then modify the state.
Delete all the FlxText found in the state.

https://github.com/ShadowMario/FNF-PsychEngine/blob/b6c64fcf3039ddc2252ee9bb4c5adc67d26d4345/source/FlashingState.hx#L18

https://github.com/ShadowMario/FNF-PsychEngine/blob/b6c64fcf3039ddc2252ee9bb4c5adc67d26d4345/source/FlashingState.hx#L26-L35

https://github.com/ShadowMario/FNF-PsychEngine/blob/b6c64fcf3039ddc2252ee9bb4c5adc67d26d4345/source/FlashingState.hx#L50

https://github.com/ShadowMario/FNF-PsychEngine/blob/b6c64fcf3039ddc2252ee9bb4c5adc67d26d4345/source/FlashingState.hx#L57-L61

Then modify `bg`. (I'm assuming that your warning image is one whole image instead of different parts.)
Delete the `.makeGraphic(FlxG.width, FlxG.height, FlxColor.BLACK);`
And modify the FlxSprite with the functions inside of it. (I'm also assuming you know how FlxSprite works.

That's pretty much it.

**Comment by tylerandari12** [comment]
This should be editable from modpacks lol...

**Comment by JacksRobotics** [comment]
> I'm guessing source. Also please add gore to da mod.
> 
> Find this line.
> 
> https://github.com/ShadowMario/FNF-PsychEngine/blob/b6c64fcf3039ddc2252ee9bb4c5adc67d26d4345/source/TitleState.hx#L452-L457
> 
> Force it to go to another state that you made. Like, lets make up the name: WarningState.hx Make that new file and you can sorta just copy the whole code from [FlashingState.hx](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/FlashingState.hx)
> 
> Then modify the state. Delete all the FlxText found in the state.
> 
> https://github.com/ShadowMario/FNF-PsychEngine/blob/b6c64fcf3039ddc2252ee9bb4c5adc67d26d4345/source/FlashingState.hx#L18
> 
> https://github.com/ShadowMario/FNF-PsychEngine/blob/b6c64fcf3039ddc2252ee9bb4c5adc67d26d4345/source/FlashingState.hx#L26-L35
> 
> https://github.com/ShadowMario/FNF-PsychEngine/blob/b6c64fcf3039ddc2252ee9bb4c5adc67d26d4345/source/FlashingState.hx#L50
> 
> https://github.com/ShadowMario/FNF-PsychEngine/blob/b6c64fcf3039ddc2252ee9bb4c5adc67d26d4345/source/FlashingState.hx#L57-L61
> 
> Then modify `bg`. (I'm assuming that your warning image is one whole image instead of different parts.) Delete the `.makeGraphic(FlxG.width, FlxG.height, FlxColor.BLACK);` And modify the FlxSprite with the functions inside of it. (I'm also assuming you know how FlxSprite works.
> 
> That's pretty much it.

Thank you.
