### ISSUE TITLE
Custom Notes Texture

### ISSUE THREAD

**Issue by Godofbacon1** [ShadowMario/FNF-PsychEngine#9181]
### Describe your problem here.

So I added the texture file for the notes in mods>images but it didnt work and if u ask me about the script i putted the exact name of the file but it didnt work can anyone help please?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Mastercopper2346** [comment]
make sure the skin is EXACTLY THE NAME of the noteskin.

**Comment by Mastercopper2346** [comment]
Hello?

**Comment by Wither362** [comment]
> Hello?

Don’t worry, sometimes takes people to answer 40 days

**Comment by Godofbacon1** [comment]
I did but it doesnt work but ill try

**Comment by frantastic24** [comment]
It's hard to tell what the problem is with just a screenshot of a file and a small part of the script
1) post the entire script
2) check note type name matches in script (case sensitive)
3) check image and XML aren't inside another folder (according to the script)
4) try with another note type and image

**Comment by Mastercopper2346** [comment]
Your LUA file name is Probably Hack note and not Hack Note

**Comment by Godofbacon1** [comment]
It Fixed Now! Its just cus i didnt add the xml to the folder with the images lol
