### ISSUE TITLE
Find note x postion?

### ISSUE THREAD

**Issue by ItsCapp** [ShadowMario/FNF-PsychEngine#923]
### What is your question?

I'm trying to write a custom event on the downloaded build.

How would I get a note's x position and use it?
something like, `currentX = getProperty(bobofdpbosb)`

**Comment by ShadowMario** [comment]
You mean strum/receptor note or hit notes?

**Strum note:**
`getPropertyFromGroup('playerStrums', 0, 'x');` or `getPropertyFromGroup('opponentStrums', 0, 'x');`
0 means Left note, change the 0 to 1/2/3 if you want to get Down, Up and Right, respectively.

**Hit notes:**
This one is a bit complex because there's `unspawnNotes` (Notes that aren't spawned yet but are cached) and `notes` so i can't explain it in words.

**Comment by ItsCapp** [comment]
This is it :) thanks!
