### ISSUE TITLE
Starting Screen Image, Changing Music from TitleState to MainMenuState, and Changing the music everytime you scroll to a different week in storymode

### ISSUE THREAD

**Issue by tdog8785** [ShadowMario/FNF-PsychEngine#9352]
### Describe your problem here.

Overview: I am making a corruption-esk mod and These are some of the main things I need help with.

Issue 1: If you have played the corruption senpai demo then you would probably know that when you open the game it gives you a couple of warnings and they are compressed into images and I just want to know how I could do this exact thing.

Issue 2: This one is pretty self explanatory. Like said before in the senpai demo the music changes when you go from the title to the main menu

Issue 3: Changing music from when you would scroll down (or up) every week.
Ex: Enter story mode and you start off on week 1 ( plays week 1 music) Scroll up one to week 7 (Plays week 7 music) Scroll down to week 2 (Plays week 2 music), etc.
Ps: I do know that at least the last issue is achievable because Corruption: Reimagined did the same thing.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Itz-Miles** [comment]
0. Shadow Mario doesn't play a lot of mods, and not a lot of people cite corruption mods because of their lack of originallity.

1. For warnings, FlashingState.hx is a warning screen that gives players the choice to enable or disable flashing lights upon first playing. you can replace images/text with your own.

2. Change the music in MainMenuState in the same way TitleState does, and make sure to change the conductor bpm to your song's

3. set a case switch up that is tied to curSelected and play/pause/stop the music accordingly. You won't have to change the bpm because going back to the main menu will change it back.

**Comment by tdog8785** [comment]
Alright Thanks
