### ISSUE TITLE
I'm working on a book mod but it broke

### ISSUE THREAD

**Issue by patreese2** [ShadowMario/FNF-PsychEngine#9428]
### Describe your bug here.

It says that some things are missing

### Command Prompt/Terminal logs (if existing)

```bash
Paths.hx (line 352)
BGSprite.hx (line 24)
PlayState.hx (line 488)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I edited daddy dearest and the background

**Comment by patreese2** [comment]
Edited the stage from week 1, changed daddy dearest to a book, and deleted some of the week 1 background files.

**Comment by ZeitHeld** [comment]
The BGs of week one are hard coded, deleting them might result into a crash-
but also replacing a whole sprite sheet with a single image, might cause issues, because it might not be in the perfect size

I'd recommend, making a mod with the utils, that Psych Engine offers. and maybe one or two tools, like the sprite sheet maker on gamebanana

**Comment by frantastic24** [comment]
close the issue

**Comment by ImaginationSuperHero528** [comment]
@patreese2 close this.

**Comment by ShadowMario** [comment]
Fucking close the issue if you've resolved it, we have god darn 300+ issues open already god damn it
![Screenshot_1](https://user-images.githubusercontent.com/44785097/177179357-0023d703-354d-4bcd-a631-253e753dd037.png)
