### ISSUE TITLE
Split Vocals & Pitch shift/song speed

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#9600]
### What feature do you want to get added on the **base** engine?

I think it would be cool, if multiple vocals would be supported. But also for general FNF
Like, you can have either one for all, or use seperated (maybe via a toggle box in charting menu). That way it can also be that bf only can be silenced, and the opponent will be perfect to hear
Though that might be quite complicated to realize (regarding that there are at least two sides to sing)

But the seocnd thing would be, that you can play the song at different speeds and the pitch goes higher or lower with it

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Swapper1** [comment]
Pitch shift: Sound useful, but it's unclear if they can make it.

Split Vocals: That an feature update for Week 8, but we can't added this yet hopefully. Otherwise...eventually, Tutorial, Monster, and Winter Horrorland do have spilt vocals which have not been used yet in the game, so I check on the [FNF wiki](https://fridaynightfunkin.fandom.com/wiki/Music)...

**Comment by Swapper1** [comment]
Here the split vocals of Bopeebo which I made in FL Studio.
[bopeebo.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/9145872/bopeebo.zip)

For Tutorial, I have to use the music stem. Because it impossible to mute the vocals when miss.
