### ISSUE TITLE
Can people like not cry about some small error every 2 seconds.

### ISSUE THREAD

**Issue by TheRealJake12** [ShadowMario/FNF-PsychEngine#9616]
### Describe your bug here.

The bug is that kids cry about some stupid error thats easily fixable. I dont think its an issue per say. Like lets say theres an error saying they forgot a ; or there needs to be a , or ). Thats not an engine issue. Its unironically a skill issue. I think there should be a no stupid error rule.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by wubbzyfan** [comment]
bruh

**Comment by Lorekeeper49** [comment]
I actually tend to get that error (very rarely though) when the needed character is clearly there.  And might I add that no amount of that character in that spot seems to do anything?  It only seems to work when I just copy the code and replace it with the copy which makes no sense since it's the exact same thing.
