### ISSUE TITLE
Null Object Reference

### ISSUE THREAD

**Issue by WillBRzado** [ShadowMario/FNF-PsychEngine#9754]
### Describe your bug here.

![imagem_2022-07-17_011816774](https://user-images.githubusercontent.com/109241009/179383750-6bf8ca06-c1bb-4455-b769-483aa56d8f4f.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No i didn't

**Comment by KillerAvecRage** [comment]
Null Object Reference, followed by a crash of the game, is an error that happens when you try to refer the engine to something that doesn't exist, in this case: it's your character, try to
find the .json in your mods->characters folder
find both the PNG and XML files in the mods->images->characters folder

If at least one of them doesn't exist, create it. It should work when you have all of them.
