### ISSUE TITLE
0.5.2 Being a piss baby

### ISSUE THREAD

**Issue by REALHaydenGaming** [ShadowMario/FNF-PsychEngine#9858]
### Describe your bug here.

Edited PlayState.hx, then terminal decide's to be a piss baby on 0.5.2, and refuse to work
![Screenshot 2022-07-22 3 14 17 AM](https://user-images.githubusercontent.com/107285739/180386622-5b860271-404a-4b09-b610-272657dd497c.png)
Showing what I changed, NOTHING.
![Screenshot 2022-07-22 3 26 34 AM](https://user-images.githubusercontent.com/107285739/180386965-3e62255a-cfff-4966-84e9-8baf373dad6a.png)
Someone, please help me, this is also an 0.5.2 error

### Command Prompt/Terminal logs (if existing)

```bash
source/PlayState.hx:2672: characters 2-8 : Expected }
source/PlayState.hx:2343: characters 3-4 : Missing ;

Refuses to fucking work on 0.5.2
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

Edited PlayState.HX, accuracy. Had 0 ACTUAL Error's

**Comment by Itz-Miles** [comment]
1. You are looking at the wrong lines.

1. If you ACTUALLY looked in the right place, you covered the ACTUAL code with a stupid drawing. We already know what to look at because of the line numbers indexed on the right.

2. If there's a segmentation fault somewhere in the code, the compiler might not know where the actual error is. It'll report at the start of the segmentation fault, and try to suggest what's causing it/where it is. (difference between the start and end of these parentheses for example)

4. 0.5.2 works fine, but your code doesn't make since. Most expressions end with a semicolon `;`

5. You deleted an ending bracket `}`, meaning one of the code blocks don't end.

6. Due to the image's contents, the post's readability, and the lack of info, you might get [`omg not dave and bambi again`](https://github.com/ShadowMario/FNF-PsychEngine/issues?q=label%3A%22omg+not+dave+%26+bambi+again%22+is%3Aclosed)ed, which renders your issue closed.

**Comment by REALHaydenGaming** [comment]
I Fixed it myself actually, closing this since I fixed it lol

**Comment by REALHaydenGaming** [comment]
Thanks for reminding me lmao, I closed all of my notifications without me knowing you commented lol!
