### ISSUE TITLE
Null object?

### ISSUE THREAD

**Issue by Bamber126** [ShadowMario/FNF-PsychEngine#9877]
### Describe your bug here.

So I was testing out my character and it gave me this error:

https://user-images.githubusercontent.com/109875558/180621609-4c7548e4-0bab-45a7-9d0d-74da76d47813.mp4

How do I fix this

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes

**Comment by KillerAvecRage** [comment]
Null Object Reference, followed by a crash of the game, is an error that happens when you try to refer the engine to something that doesn't exist, in this case: it's your character, try to
find the .json in your mods->characters folder
find both the PNG and XML files in the mods->images->characters folder

If at least one of them doesn't exist, create it. It should work when you have all of them.

**Comment by Bamber126** [comment]
Thank you but I just fixed the problem and it works now
